using System;

namespace VectorIcons
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by GlyphJsonToCsharp.
    /// </summary>
    public static partial class AntDesignFont
    {
        /// <summary>
        /// fa-stepforward unicode value ("\ue600").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Stepforward = "\ue600";

        /// <summary>
        /// fa-stepbackward unicode value ("\ue601").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Stepbackward = "\ue601";

        /// <summary>
        /// fa-forward unicode value ("\ue602").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Forward = "\ue602";

        /// <summary>
        /// fa-banckward unicode value ("\ue603").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Banckward = "\ue603";

        /// <summary>
        /// fa-caretright unicode value ("\ue604").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Caretright = "\ue604";

        /// <summary>
        /// fa-caretleft unicode value ("\ue605").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Caretleft = "\ue605";

        /// <summary>
        /// fa-caretdown unicode value ("\ue606").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Caretdown = "\ue606";

        /// <summary>
        /// fa-caretup unicode value ("\ue607").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Caretup = "\ue607";

        /// <summary>
        /// fa-rightcircle unicode value ("\ue608").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Rightcircle = "\ue608";

        /// <summary>
        /// fa-leftcircle unicode value ("\ue609").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Leftcircle = "\ue609";

        /// <summary>
        /// fa-upcircle unicode value ("\ue60a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Upcircle = "\ue60a";

        /// <summary>
        /// fa-downcircle unicode value ("\ue60b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Downcircle = "\ue60b";

        /// <summary>
        /// fa-rightcircleo unicode value ("\ue60c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Rightcircleo = "\ue60c";

        /// <summary>
        /// fa-leftcircleo unicode value ("\ue60d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Leftcircleo = "\ue60d";

        /// <summary>
        /// fa-upcircleo unicode value ("\ue60e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Upcircleo = "\ue60e";

        /// <summary>
        /// fa-downcircleo unicode value ("\ue60f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Downcircleo = "\ue60f";

        /// <summary>
        /// fa-verticleleft unicode value ("\ue610").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Verticleleft = "\ue610";

        /// <summary>
        /// fa-verticleright unicode value ("\ue611").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Verticleright = "\ue611";

        /// <summary>
        /// fa-back unicode value ("\ue612").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Back = "\ue612";

        /// <summary>
        /// fa-retweet unicode value ("\ue613").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Retweet = "\ue613";

        /// <summary>
        /// fa-shrink unicode value ("\ue614").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Shrink = "\ue614";

        /// <summary>
        /// fa-arrowsalt unicode value ("\ue615").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Arrowsalt = "\ue615";

        /// <summary>
        /// fa-doubleright unicode value ("\ue617").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Doubleright = "\ue617";

        /// <summary>
        /// fa-doubleleft unicode value ("\ue618").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Doubleleft = "\ue618";

        /// <summary>
        /// fa-arrowdown unicode value ("\ue619").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Arrowdown = "\ue619";

        /// <summary>
        /// fa-arrowup unicode value ("\ue61a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Arrowup = "\ue61a";

        /// <summary>
        /// fa-arrowright unicode value ("\ue61b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Arrowright = "\ue61b";

        /// <summary>
        /// fa-arrowleft unicode value ("\ue61c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Arrowleft = "\ue61c";

        /// <summary>
        /// fa-down unicode value ("\ue61d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Down = "\ue61d";

        /// <summary>
        /// fa-up unicode value ("\ue61e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Up = "\ue61e";

        /// <summary>
        /// fa-right unicode value ("\ue61f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Right = "\ue61f";

        /// <summary>
        /// fa-left unicode value ("\ue620").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Left = "\ue620";

        /// <summary>
        /// fa-minussquareo unicode value ("\ue621").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Minussquareo = "\ue621";

        /// <summary>
        /// fa-minuscircle unicode value ("\ue622").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Minuscircle = "\ue622";

        /// <summary>
        /// fa-minuscircleo unicode value ("\ue623").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Minuscircleo = "\ue623";

        /// <summary>
        /// fa-minus unicode value ("\ue624").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Minus = "\ue624";

        /// <summary>
        /// fa-pluscircleo unicode value ("\ue625").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pluscircleo = "\ue625";

        /// <summary>
        /// fa-pluscircle unicode value ("\ue626").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pluscircle = "\ue626";

        /// <summary>
        /// fa-plus unicode value ("\ue627").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Plus = "\ue627";

        /// <summary>
        /// fa-infocirlce unicode value ("\ue628").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Infocirlce = "\ue628";

        /// <summary>
        /// fa-infocirlceo unicode value ("\ue629").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Infocirlceo = "\ue629";

        /// <summary>
        /// fa-info unicode value ("\ue62a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Info = "\ue62a";

        /// <summary>
        /// fa-exclamation unicode value ("\ue62b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Exclamation = "\ue62b";

        /// <summary>
        /// fa-exclamationcircle unicode value ("\ue62c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Exclamationcircle = "\ue62c";

        /// <summary>
        /// fa-exclamationcircleo unicode value ("\ue62d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Exclamationcircleo = "\ue62d";

        /// <summary>
        /// fa-closecircle unicode value ("\ue62e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Closecircle = "\ue62e";

        /// <summary>
        /// fa-closecircleo unicode value ("\ue62f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Closecircleo = "\ue62f";

        /// <summary>
        /// fa-checkcircle unicode value ("\ue630").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Checkcircle = "\ue630";

        /// <summary>
        /// fa-checkcircleo unicode value ("\ue631").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Checkcircleo = "\ue631";

        /// <summary>
        /// fa-check unicode value ("\ue632").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Check = "\ue632";

        /// <summary>
        /// fa-close unicode value ("\ue633").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Close = "\ue633";

        /// <summary>
        /// fa-customerservice unicode value ("\ue634").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Customerservice = "\ue634";

        /// <summary>
        /// fa-creditcard unicode value ("\ue635").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Creditcard = "\ue635";

        /// <summary>
        /// fa-codesquareo unicode value ("\ue636").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Codesquareo = "\ue636";

        /// <summary>
        /// fa-book unicode value ("\ue637").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Book = "\ue637";

        /// <summary>
        /// fa-barschart unicode value ("\ue638").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Barschart = "\ue638";

        /// <summary>
        /// fa-bars unicode value ("\ue639").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bars = "\ue639";

        /// <summary>
        /// fa-question unicode value ("\ue63a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Question = "\ue63a";

        /// <summary>
        /// fa-questioncircle unicode value ("\ue63b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Questioncircle = "\ue63b";

        /// <summary>
        /// fa-questioncircleo unicode value ("\ue63c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Questioncircleo = "\ue63c";

        /// <summary>
        /// fa-pause unicode value ("\ue63d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pause = "\ue63d";

        /// <summary>
        /// fa-pausecircle unicode value ("\ue63e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pausecircle = "\ue63e";

        /// <summary>
        /// fa-pausecircleo unicode value ("\ue63f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pausecircleo = "\ue63f";

        /// <summary>
        /// fa-clockcircle unicode value ("\ue640").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Clockcircle = "\ue640";

        /// <summary>
        /// fa-clockcircleo unicode value ("\ue641").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Clockcircleo = "\ue641";

        /// <summary>
        /// fa-swap unicode value ("\ue642").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Swap = "\ue642";

        /// <summary>
        /// fa-swapleft unicode value ("\ue643").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Swapleft = "\ue643";

        /// <summary>
        /// fa-swapright unicode value ("\ue644").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Swapright = "\ue644";

        /// <summary>
        /// fa-plussquareo unicode value ("\ue645").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Plussquareo = "\ue645";

        /// <summary>
        /// fa-frown unicode value ("\ue646").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Frown = "\ue646";

        /// <summary>
        /// fa-menufold unicode value ("\ue658").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Menufold = "\ue658";

        /// <summary>
        /// fa-mail unicode value ("\ue659").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Mail = "\ue659";

        /// <summary>
        /// fa-link unicode value ("\ue65b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Link = "\ue65b";

        /// <summary>
        /// fa-areachart unicode value ("\ue65c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Areachart = "\ue65c";

        /// <summary>
        /// fa-linechart unicode value ("\ue65d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Linechart = "\ue65d";

        /// <summary>
        /// fa-home unicode value ("\ue65e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Home = "\ue65e";

        /// <summary>
        /// fa-laptop unicode value ("\ue65f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Laptop = "\ue65f";

        /// <summary>
        /// fa-star unicode value ("\ue660").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Star = "\ue660";

        /// <summary>
        /// fa-staro unicode value ("\ue661").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Staro = "\ue661";

        /// <summary>
        /// fa-filter unicode value ("\ue663").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Filter = "\ue663";

        /// <summary>
        /// fa-meho unicode value ("\ue666").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Meho = "\ue666";

        /// <summary>
        /// fa-meh unicode value ("\ue667").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Meh = "\ue667";

        /// <summary>
        /// fa-shoppingcart unicode value ("\ue668").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Shoppingcart = "\ue668";

        /// <summary>
        /// fa-save unicode value ("\ue669").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Save = "\ue669";

        /// <summary>
        /// fa-user unicode value ("\ue66a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string User = "\ue66a";

        /// <summary>
        /// fa-videocamera unicode value ("\ue66b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Videocamera = "\ue66b";

        /// <summary>
        /// fa-totop unicode value ("\ue66c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Totop = "\ue66c";

        /// <summary>
        /// fa-team unicode value ("\ue66d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Team = "\ue66d";

        /// <summary>
        /// fa-sharealt unicode value ("\ue671").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Sharealt = "\ue671";

        /// <summary>
        /// fa-setting unicode value ("\ue672").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Setting = "\ue672";

        /// <summary>
        /// fa-picture unicode value ("\ue674").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Picture = "\ue674";

        /// <summary>
        /// fa-phone unicode value ("\ue675").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Phone = "\ue675";

        /// <summary>
        /// fa-paperclip unicode value ("\ue676").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Paperclip = "\ue676";

        /// <summary>
        /// fa-notification unicode value ("\ue677").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Notification = "\ue677";

        /// <summary>
        /// fa-menuunfold unicode value ("\ue679").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Menuunfold = "\ue679";

        /// <summary>
        /// fa-inbox unicode value ("\ue67a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Inbox = "\ue67a";

        /// <summary>
        /// fa-lock unicode value ("\ue67b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Lock = "\ue67b";

        /// <summary>
        /// fa-qrcode unicode value ("\ue67c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Qrcode = "\ue67c";

        /// <summary>
        /// fa-tags unicode value ("\ue67d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Tags = "\ue67d";

        /// <summary>
        /// fa-tagso unicode value ("\ue67e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Tagso = "\ue67e";

        /// <summary>
        /// fa-cloudo unicode value ("\ue67f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Cloudo = "\ue67f";

        /// <summary>
        /// fa-cloud unicode value ("\ue680").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Cloud = "\ue680";

        /// <summary>
        /// fa-cloudupload unicode value ("\ue681").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Cloudupload = "\ue681";

        /// <summary>
        /// fa-clouddownload unicode value ("\ue682").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Clouddownload = "\ue682";

        /// <summary>
        /// fa-clouddownloado unicode value ("\ue683").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Clouddownloado = "\ue683";

        /// <summary>
        /// fa-clouduploado unicode value ("\ue684").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Clouduploado = "\ue684";

        /// <summary>
        /// fa-enviroment unicode value ("\ue685").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Enviroment = "\ue685";

        /// <summary>
        /// fa-enviromento unicode value ("\ue686").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Enviromento = "\ue686";

        /// <summary>
        /// fa-eye unicode value ("\ue687").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Eye = "\ue687";

        /// <summary>
        /// fa-eyeo unicode value ("\ue688").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Eyeo = "\ue688";

        /// <summary>
        /// fa-camera unicode value ("\ue689").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Camera = "\ue689";

        /// <summary>
        /// fa-camerao unicode value ("\ue68a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Camerao = "\ue68a";

        /// <summary>
        /// fa-windows unicode value ("\ue68b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Windows = "\ue68b";

        /// <summary>
        /// fa-export2 unicode value ("\ue690").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Export2 = "\ue690";

        /// <summary>
        /// fa-export unicode value ("\ue691").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Export = "\ue691";

        /// <summary>
        /// fa-circledowno unicode value ("\ue693").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Circledowno = "\ue693";

        /// <summary>
        /// fa-circledown unicode value ("\ue694").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Circledown = "\ue694";

        /// <summary>
        /// fa-hdd unicode value ("\ue69a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Hdd = "\ue69a";

        /// <summary>
        /// fa-ie unicode value ("\ue69b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Ie = "\ue69b";

        /// <summary>
        /// fa-delete unicode value ("\ue69f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Delete = "\ue69f";

        /// <summary>
        /// fa-enter unicode value ("\ue6a0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Enter = "\ue6a0";

        /// <summary>
        /// fa-pushpino unicode value ("\ue6a1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pushpino = "\ue6a1";

        /// <summary>
        /// fa-pushpin unicode value ("\ue6a2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pushpin = "\ue6a2";

        /// <summary>
        /// fa-heart unicode value ("\ue6a3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Heart = "\ue6a3";

        /// <summary>
        /// fa-hearto unicode value ("\ue6a4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Hearto = "\ue6a4";

        /// <summary>
        /// fa-smile-circle unicode value ("\ue6a7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SmileCircle = "\ue6a7";

        /// <summary>
        /// fa-smileo unicode value ("\ue6a8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Smileo = "\ue6a8";

        /// <summary>
        /// fa-frowno unicode value ("\ue6a9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Frowno = "\ue6a9";

        /// <summary>
        /// fa-calculator unicode value ("\ue6aa").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Calculator = "\ue6aa";

        /// <summary>
        /// fa-chrome unicode value ("\ue6ac").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Chrome = "\ue6ac";

        /// <summary>
        /// fa-github unicode value ("\ue6ad").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Github = "\ue6ad";

        /// <summary>
        /// fa-iconfontdesktop unicode value ("\ue6b4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Iconfontdesktop = "\ue6b4";

        /// <summary>
        /// fa-caretcircleoup unicode value ("\ue6b5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Caretcircleoup = "\ue6b5";

        /// <summary>
        /// fa-upload unicode value ("\ue6b6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Upload = "\ue6b6";

        /// <summary>
        /// fa-download unicode value ("\ue6b7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Download = "\ue6b7";

        /// <summary>
        /// fa-piechart unicode value ("\ue6b8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Piechart = "\ue6b8";

        /// <summary>
        /// fa-lock1 unicode value ("\ue6b9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Lock1 = "\ue6b9";

        /// <summary>
        /// fa-unlock unicode value ("\ue6ba").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Unlock = "\ue6ba";

        /// <summary>
        /// fa-windowso unicode value ("\ue6bc").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Windowso = "\ue6bc";

        /// <summary>
        /// fa-dotchart unicode value ("\ue6bd").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Dotchart = "\ue6bd";

        /// <summary>
        /// fa-barchart unicode value ("\ue6be").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Barchart = "\ue6be";

        /// <summary>
        /// fa-codesquare unicode value ("\ue6bf").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Codesquare = "\ue6bf";

        /// <summary>
        /// fa-plussquare unicode value ("\ue6c0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Plussquare = "\ue6c0";

        /// <summary>
        /// fa-minussquare unicode value ("\ue6c1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Minussquare = "\ue6c1";

        /// <summary>
        /// fa-closesquare unicode value ("\ue6c2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Closesquare = "\ue6c2";

        /// <summary>
        /// fa-closesquareo unicode value ("\ue6c3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Closesquareo = "\ue6c3";

        /// <summary>
        /// fa-checksquare unicode value ("\ue6c4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Checksquare = "\ue6c4";

        /// <summary>
        /// fa-checksquareo unicode value ("\ue6c5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Checksquareo = "\ue6c5";

        /// <summary>
        /// fa-fastbackward unicode value ("\ue6c6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Fastbackward = "\ue6c6";

        /// <summary>
        /// fa-fastforward unicode value ("\ue6c7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Fastforward = "\ue6c7";

        /// <summary>
        /// fa-upsquare unicode value ("\ue6c8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Upsquare = "\ue6c8";

        /// <summary>
        /// fa-downsquare unicode value ("\ue6c9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Downsquare = "\ue6c9";

        /// <summary>
        /// fa-leftsquare unicode value ("\ue6ca").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Leftsquare = "\ue6ca";

        /// <summary>
        /// fa-rightsquare unicode value ("\ue6cb").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Rightsquare = "\ue6cb";

        /// <summary>
        /// fa-rightsquareo unicode value ("\ue6cc").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Rightsquareo = "\ue6cc";

        /// <summary>
        /// fa-leftsquareo unicode value ("\ue6cd").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Leftsquareo = "\ue6cd";

        /// <summary>
        /// fa-down-square-o unicode value ("\ue6ce").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DownSquareO = "\ue6ce";

        /// <summary>
        /// fa-up-square-o unicode value ("\ue6cf").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string UpSquareO = "\ue6cf";

        /// <summary>
        /// fa-play unicode value ("\ue6d0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Play = "\ue6d0";

        /// <summary>
        /// fa-playcircleo unicode value ("\ue6d1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Playcircleo = "\ue6d1";

        /// <summary>
        /// fa-tag unicode value ("\ue6d2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Tag = "\ue6d2";

        /// <summary>
        /// fa-tago unicode value ("\ue6d3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Tago = "\ue6d3";

        /// <summary>
        /// fa-addfile unicode value ("\ue910").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Addfile = "\ue910";

        /// <summary>
        /// fa-folder1 unicode value ("\ue662").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Folder1 = "\ue662";

        /// <summary>
        /// fa-file1 unicode value ("\ue664").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string File1 = "\ue664";

        /// <summary>
        /// fa-switcher unicode value ("\ue913").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Switcher = "\ue913";

        /// <summary>
        /// fa-addfolder unicode value ("\ue914").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Addfolder = "\ue914";

        /// <summary>
        /// fa-folderopen unicode value ("\ue699").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Folderopen = "\ue699";

        /// <summary>
        /// fa-search1 unicode value ("\ue670").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Search1 = "\ue670";

        /// <summary>
        /// fa-ellipsis1 unicode value ("\ue647").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Ellipsis1 = "\ue647";

        /// <summary>
        /// fa-calendar unicode value ("\ue6bb").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Calendar = "\ue6bb";

        /// <summary>
        /// fa-filetext1 unicode value ("\ue698").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Filetext1 = "\ue698";

        /// <summary>
        /// fa-copy1 unicode value ("\ue648").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Copy1 = "\ue648";

        /// <summary>
        /// fa-jpgfile1 unicode value ("\ue69c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Jpgfile1 = "\ue69c";

        /// <summary>
        /// fa-pdffile1 unicode value ("\ue6b3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pdffile1 = "\ue6b3";

        /// <summary>
        /// fa-exclefile1 unicode value ("\ue6b0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Exclefile1 = "\ue6b0";

        /// <summary>
        /// fa-pptfile1 unicode value ("\ue6b1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pptfile1 = "\ue6b1";

        /// <summary>
        /// fa-unknowfile1 unicode value ("\ue6af").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Unknowfile1 = "\ue6af";

        /// <summary>
        /// fa-wordfile1 unicode value ("\ue6b2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Wordfile1 = "\ue6b2";

        /// <summary>
        /// fa-dingding unicode value ("\ue923").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Dingding = "\ue923";

        /// <summary>
        /// fa-dingding-o unicode value ("\ue925").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DingdingO = "\ue925";

        /// <summary>
        /// fa-mobile1 unicode value ("\ue678").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Mobile1 = "\ue678";

        /// <summary>
        /// fa-tablet1 unicode value ("\ue66e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Tablet1 = "\ue66e";

        /// <summary>
        /// fa-bells unicode value ("\ue64e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bells = "\ue64e";

        /// <summary>
        /// fa-disconnect unicode value ("\ue64f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Disconnect = "\ue64f";

        /// <summary>
        /// fa-database unicode value ("\ue650").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Database = "\ue650";

        /// <summary>
        /// fa-barcode unicode value ("\ue652").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Barcode = "\ue652";

        /// <summary>
        /// fa-hourglass unicode value ("\ue653").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Hourglass = "\ue653";

        /// <summary>
        /// fa-key unicode value ("\ue654").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Key = "\ue654";

        /// <summary>
        /// fa-flag unicode value ("\ue655").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Flag = "\ue655";

        /// <summary>
        /// fa-layout unicode value ("\ue656").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Layout = "\ue656";

        /// <summary>
        /// fa-printer unicode value ("\ue673").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Printer = "\ue673";

        /// <summary>
        /// fa-USB unicode value ("\ue6d7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string USB = "\ue6d7";

        /// <summary>
        /// fa-skin unicode value ("\ue6d8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Skin = "\ue6d8";

        /// <summary>
        /// fa-tool unicode value ("\ue6d9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Tool = "\ue6d9";

        /// <summary>
        /// fa-car unicode value ("\ue6dc").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Car = "\ue6dc";

        /// <summary>
        /// fa-addusergroup unicode value ("\ue6dd").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Addusergroup = "\ue6dd";

        /// <summary>
        /// fa-carryout unicode value ("\ue6df").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Carryout = "\ue6df";

        /// <summary>
        /// fa-deleteuser unicode value ("\ue6e0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Deleteuser = "\ue6e0";

        /// <summary>
        /// fa-deleteusergroup unicode value ("\ue6e1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Deleteusergroup = "\ue6e1";

        /// <summary>
        /// fa-man unicode value ("\ue6e2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Man = "\ue6e2";

        /// <summary>
        /// fa-isv unicode value ("\ue6e3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Isv = "\ue6e3";

        /// <summary>
        /// fa-gift unicode value ("\ue6e4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Gift = "\ue6e4";

        /// <summary>
        /// fa-idcard unicode value ("\ue6e5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Idcard = "\ue6e5";

        /// <summary>
        /// fa-medicinebox unicode value ("\ue6e6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Medicinebox = "\ue6e6";

        /// <summary>
        /// fa-redenvelopes unicode value ("\ue6e7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Redenvelopes = "\ue6e7";

        /// <summary>
        /// fa-rest unicode value ("\ue6e8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Rest = "\ue6e8";

        /// <summary>
        /// fa-Safety unicode value ("\ue6ea").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Safety = "\ue6ea";

        /// <summary>
        /// fa-wallet unicode value ("\ue6eb").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Wallet = "\ue6eb";

        /// <summary>
        /// fa-woman unicode value ("\ue6ec").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Woman = "\ue6ec";

        /// <summary>
        /// fa-adduser unicode value ("\ue6ed").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Adduser = "\ue6ed";

        /// <summary>
        /// fa-bank unicode value ("\ue6ee").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bank = "\ue6ee";

        /// <summary>
        /// fa-Trophy unicode value ("\ue6ef").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Trophy = "\ue6ef";

        /// <summary>
        /// fa-loading1 unicode value ("\ue6ae").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Loading1 = "\ue6ae";

        /// <summary>
        /// fa-loading2 unicode value ("\ue64d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Loading2 = "\ue64d";

        /// <summary>
        /// fa-like2 unicode value ("\ue69d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Like2 = "\ue69d";

        /// <summary>
        /// fa-dislike2 unicode value ("\ue69e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Dislike2 = "\ue69e";

        /// <summary>
        /// fa-like1 unicode value ("\ue64c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Like1 = "\ue64c";

        /// <summary>
        /// fa-dislike1 unicode value ("\ue64b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Dislike1 = "\ue64b";

        /// <summary>
        /// fa-bulb1 unicode value ("\ue649").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bulb1 = "\ue649";

        /// <summary>
        /// fa-rocket1 unicode value ("\ue90f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Rocket1 = "\ue90f";

        /// <summary>
        /// fa-select1 unicode value ("\ue64a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Select1 = "\ue64a";

        /// <summary>
        /// fa-apple1 unicode value ("\ue68c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Apple1 = "\ue68c";

        /// <summary>
        /// fa-apple-o unicode value ("\ue6d4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AppleO = "\ue6d4";

        /// <summary>
        /// fa-android1 unicode value ("\ue938").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Android1 = "\ue938";

        /// <summary>
        /// fa-android unicode value ("\ue68d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Android = "\ue68d";

        /// <summary>
        /// fa-aliwangwang-o1 unicode value ("\ue68f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AliwangwangO1 = "\ue68f";

        /// <summary>
        /// fa-aliwangwang unicode value ("\ue68e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Aliwangwang = "\ue68e";

        /// <summary>
        /// fa-pay-circle1 unicode value ("\ue6a5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PayCircle1 = "\ue6a5";

        /// <summary>
        /// fa-pay-circle-o1 unicode value ("\ue6a6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PayCircleO1 = "\ue6a6";

        /// <summary>
        /// fa-poweroff unicode value ("\ue6d5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Poweroff = "\ue6d5";

        /// <summary>
        /// fa-trademark unicode value ("\ue651").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Trademark = "\ue651";

        /// <summary>
        /// fa-find unicode value ("\ue6db").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Find = "\ue6db";

        /// <summary>
        /// fa-copyright unicode value ("\ue6de").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Copyright = "\ue6de";

        /// <summary>
        /// fa-sound unicode value ("\ue6e9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Sound = "\ue6e9";

        /// <summary>
        /// fa-earth unicode value ("\ue6f1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Earth = "\ue6f1";

        /// <summary>
        /// fa-wifi unicode value ("\ue6d6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Wifi = "\ue6d6";

        /// <summary>
        /// fa-sync unicode value ("\ue6da").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Sync = "\ue6da";

        /// <summary>
        /// fa-login unicode value ("\ue657").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Login = "\ue657";

        /// <summary>
        /// fa-logout unicode value ("\ue65a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Logout = "\ue65a";

        /// <summary>
        /// fa-reload1 unicode value ("\ue616").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Reload1 = "\ue616";

        /// <summary>
        /// fa-message1 unicode value ("\ue6ab").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Message1 = "\ue6ab";

        /// <summary>
        /// fa-shake unicode value ("\ue94f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Shake = "\ue94f";

        /// <summary>
        /// fa-API unicode value ("\ue951").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string API = "\ue951";

        /// <summary>
        /// fa-appstore-o unicode value ("\ue695").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AppstoreO = "\ue695";

        /// <summary>
        /// fa-appstore1 unicode value ("\ue696").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Appstore1 = "\ue696";

        /// <summary>
        /// fa-scan1 unicode value ("\ue697").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Scan1 = "\ue697";

        /// <summary>
        /// fa-exception1 unicode value ("\ue665").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Exception1 = "\ue665";

        /// <summary>
        /// fa-contacts unicode value ("\ue6f0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Contacts = "\ue6f0";

        /// <summary>
        /// fa-solution1 unicode value ("\ue66f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Solution1 = "\ue66f";

        /// <summary>
        /// fa-fork unicode value ("\ue6f2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Fork = "\ue6f2";

        /// <summary>
        /// fa-edit unicode value ("\ue692").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Edit = "\ue692";

        /// <summary>
        /// fa-form unicode value ("\ue996").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Form = "\ue996";

        /// <summary>
        /// fa-warning unicode value ("\ue997").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Warning = "\ue997";

        /// <summary>
        /// fa-table unicode value ("\ue998").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Table = "\ue998";

        /// <summary>
        /// fa-profile unicode value ("\ue999").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Profile = "\ue999";

        /// <summary>
        /// fa-dashboard unicode value ("\ue99a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Dashboard = "\ue99a";

        /// <summary>
        /// fa-indent-left unicode value ("\ue9a6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string IndentLeft = "\ue9a6";

        /// <summary>
        /// fa-indent-right unicode value ("\ue9a7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string IndentRight = "\ue9a7";

        /// <summary>
        /// fa-menu-unfold unicode value ("\ue9ac").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MenuUnfold = "\ue9ac";

        /// <summary>
        /// fa-menu-fold unicode value ("\ue9ad").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MenuFold = "\ue9ad";

        /// <summary>
        /// fa-antdesign unicode value ("\ue9b2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Antdesign = "\ue9b2";

        /// <summary>
        /// fa-alipay-square unicode value ("\ue9b3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AlipaySquare = "\ue9b3";

        /// <summary>
        /// fa-codepen-circle unicode value ("\ue9b4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CodepenCircle = "\ue9b4";

        /// <summary>
        /// fa-google unicode value ("\ue9b5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Google = "\ue9b5";

        /// <summary>
        /// fa-amazon unicode value ("\ue9b6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Amazon = "\ue9b6";

        /// <summary>
        /// fa-codepen unicode value ("\ue9b7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Codepen = "\ue9b7";

        /// <summary>
        /// fa-facebook-square unicode value ("\ue9b8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FacebookSquare = "\ue9b8";

        /// <summary>
        /// fa-dropbox unicode value ("\ue9b9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Dropbox = "\ue9b9";

        /// <summary>
        /// fa-googleplus unicode value ("\ue9ba").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Googleplus = "\ue9ba";

        /// <summary>
        /// fa-linkedin-square unicode value ("\ue9bb").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string LinkedinSquare = "\ue9bb";

        /// <summary>
        /// fa-medium-monogram unicode value ("\ue9bc").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MediumMonogram = "\ue9bc";

        /// <summary>
        /// fa-gitlab unicode value ("\ue9bd").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Gitlab = "\ue9bd";

        /// <summary>
        /// fa-medium-wordmark unicode value ("\ue9be").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MediumWordmark = "\ue9be";

        /// <summary>
        /// fa-QQ unicode value ("\ue9bf").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string QQ = "\ue9bf";

        /// <summary>
        /// fa-skype unicode value ("\ue9c0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Skype = "\ue9c0";

        /// <summary>
        /// fa-taobao-square unicode value ("\ue9c1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TaobaoSquare = "\ue9c1";

        /// <summary>
        /// fa-alipay-circle unicode value ("\ue9c2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AlipayCircle = "\ue9c2";

        /// <summary>
        /// fa-youtube unicode value ("\ue9c3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Youtube = "\ue9c3";

        /// <summary>
        /// fa-wechat unicode value ("\ue9c4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Wechat = "\ue9c4";

        /// <summary>
        /// fa-twitter unicode value ("\ue9c5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Twitter = "\ue9c5";

        /// <summary>
        /// fa-weibo unicode value ("\ue9c6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Weibo = "\ue9c6";

        /// <summary>
        /// fa-HTML unicode value ("\ue9c7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string HTML = "\ue9c7";

        /// <summary>
        /// fa-taobao-circle unicode value ("\ue6f3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TaobaoCircle = "\ue6f3";

        /// <summary>
        /// fa-weibo-circle unicode value ("\ue6f4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string WeiboCircle = "\ue6f4";

        /// <summary>
        /// fa-weibo-square unicode value ("\ue6f5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string WeiboSquare = "\ue6f5";

        /// <summary>
        /// fa-CodeSandbox unicode value ("\ue9d4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CodeSandbox = "\ue9d4";

        /// <summary>
        /// fa-aliyun unicode value ("\ue9f4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Aliyun = "\ue9f4";

        /// <summary>
        /// fa-zhihu unicode value ("\ue703").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Zhihu = "\ue703";

        /// <summary>
        /// fa-behance unicode value ("\ue707").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Behance = "\ue707";

        /// <summary>
        /// fa-dribbble unicode value ("\ue709").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Dribbble = "\ue709";

        /// <summary>
        /// fa-dribbble-square unicode value ("\ue70a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DribbbleSquare = "\ue70a";

        /// <summary>
        /// fa-behance-square unicode value ("\ue708").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string BehanceSquare = "\ue708";

        /// <summary>
        /// fa-file-markdown unicode value ("\ue704").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FileMarkdown = "\ue704";

        /// <summary>
        /// fa-instagram unicode value ("\ue70b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Instagram = "\ue70b";

        /// <summary>
        /// fa-yuque unicode value ("\ue70c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Yuque = "\ue70c";

        /// <summary>
        /// fa-slack unicode value ("\ue705").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Slack = "\ue705";

        /// <summary>
        /// fa-slack-square unicode value ("\ue706").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SlackSquare = "\ue706";
    }
}
