using System;

namespace VectorIcons
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by GlyphJsonToCsharp.
    /// </summary>
    public static partial class EvilIconsFont
    {
        /// <summary>
        /// fa-archive unicode value ("\uf100").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Archive = "\uf100";

        /// <summary>
        /// fa-arrow-down unicode value ("\uf101").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowDown = "\uf101";

        /// <summary>
        /// fa-arrow-left unicode value ("\uf102").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowLeft = "\uf102";

        /// <summary>
        /// fa-arrow-right unicode value ("\uf103").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowRight = "\uf103";

        /// <summary>
        /// fa-arrow-up unicode value ("\uf104").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowUp = "\uf104";

        /// <summary>
        /// fa-bell unicode value ("\uf105").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bell = "\uf105";

        /// <summary>
        /// fa-calendar unicode value ("\uf106").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Calendar = "\uf106";

        /// <summary>
        /// fa-camera unicode value ("\uf107").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Camera = "\uf107";

        /// <summary>
        /// fa-cart unicode value ("\uf108").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Cart = "\uf108";

        /// <summary>
        /// fa-chart unicode value ("\uf109").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Chart = "\uf109";

        /// <summary>
        /// fa-check unicode value ("\uf10a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Check = "\uf10a";

        /// <summary>
        /// fa-chevron-down unicode value ("\uf10b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ChevronDown = "\uf10b";

        /// <summary>
        /// fa-chevron-left unicode value ("\uf10c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ChevronLeft = "\uf10c";

        /// <summary>
        /// fa-chevron-right unicode value ("\uf10d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ChevronRight = "\uf10d";

        /// <summary>
        /// fa-chevron-up unicode value ("\uf10e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ChevronUp = "\uf10e";

        /// <summary>
        /// fa-clock unicode value ("\uf10f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Clock = "\uf10f";

        /// <summary>
        /// fa-close unicode value ("\uf110").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Close = "\uf110";

        /// <summary>
        /// fa-close-o unicode value ("\uf111").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CloseO = "\uf111";

        /// <summary>
        /// fa-comment unicode value ("\uf112").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Comment = "\uf112";

        /// <summary>
        /// fa-credit-card unicode value ("\uf113").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CreditCard = "\uf113";

        /// <summary>
        /// fa-envelope unicode value ("\uf114").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Envelope = "\uf114";

        /// <summary>
        /// fa-exclamation unicode value ("\uf115").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Exclamation = "\uf115";

        /// <summary>
        /// fa-external-link unicode value ("\uf116").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ExternalLink = "\uf116";

        /// <summary>
        /// fa-eye unicode value ("\uf117").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Eye = "\uf117";

        /// <summary>
        /// fa-gear unicode value ("\uf118").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Gear = "\uf118";

        /// <summary>
        /// fa-heart unicode value ("\uf119").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Heart = "\uf119";

        /// <summary>
        /// fa-image unicode value ("\uf11a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Image = "\uf11a";

        /// <summary>
        /// fa-like unicode value ("\uf11b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Like = "\uf11b";

        /// <summary>
        /// fa-link unicode value ("\uf11c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Link = "\uf11c";

        /// <summary>
        /// fa-location unicode value ("\uf11d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Location = "\uf11d";

        /// <summary>
        /// fa-lock unicode value ("\uf11e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Lock = "\uf11e";

        /// <summary>
        /// fa-minus unicode value ("\uf11f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Minus = "\uf11f";

        /// <summary>
        /// fa-navicon unicode value ("\uf120").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Navicon = "\uf120";

        /// <summary>
        /// fa-paperclip unicode value ("\uf121").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Paperclip = "\uf121";

        /// <summary>
        /// fa-pencil unicode value ("\uf122").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pencil = "\uf122";

        /// <summary>
        /// fa-play unicode value ("\uf123").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Play = "\uf123";

        /// <summary>
        /// fa-plus unicode value ("\uf124").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Plus = "\uf124";

        /// <summary>
        /// fa-pointer unicode value ("\uf125").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pointer = "\uf125";

        /// <summary>
        /// fa-question unicode value ("\uf126").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Question = "\uf126";

        /// <summary>
        /// fa-redo unicode value ("\uf127").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Redo = "\uf127";

        /// <summary>
        /// fa-refresh unicode value ("\uf128").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Refresh = "\uf128";

        /// <summary>
        /// fa-retweet unicode value ("\uf129").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Retweet = "\uf129";

        /// <summary>
        /// fa-sc-facebook unicode value ("\uf12a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScFacebook = "\uf12a";

        /// <summary>
        /// fa-sc-github unicode value ("\uf12b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScGithub = "\uf12b";

        /// <summary>
        /// fa-sc-google-plus unicode value ("\uf12c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScGooglePlus = "\uf12c";

        /// <summary>
        /// fa-sc-instagram unicode value ("\uf12d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScInstagram = "\uf12d";

        /// <summary>
        /// fa-sc-linkedin unicode value ("\uf12e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScLinkedin = "\uf12e";

        /// <summary>
        /// fa-sc-odnoklassniki unicode value ("\uf12f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScOdnoklassniki = "\uf12f";

        /// <summary>
        /// fa-sc-pinterest unicode value ("\uf130").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScPinterest = "\uf130";

        /// <summary>
        /// fa-sc-skype unicode value ("\uf131").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScSkype = "\uf131";

        /// <summary>
        /// fa-sc-soundcloud unicode value ("\uf132").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScSoundcloud = "\uf132";

        /// <summary>
        /// fa-sc-telegram unicode value ("\uf133").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScTelegram = "\uf133";

        /// <summary>
        /// fa-sc-tumblr unicode value ("\uf134").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScTumblr = "\uf134";

        /// <summary>
        /// fa-sc-twitter unicode value ("\uf135").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScTwitter = "\uf135";

        /// <summary>
        /// fa-sc-vimeo unicode value ("\uf136").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScVimeo = "\uf136";

        /// <summary>
        /// fa-sc-vk unicode value ("\uf137").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScVk = "\uf137";

        /// <summary>
        /// fa-sc-youtube unicode value ("\uf138").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScYoutube = "\uf138";

        /// <summary>
        /// fa-search unicode value ("\uf139").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Search = "\uf139";

        /// <summary>
        /// fa-share-apple unicode value ("\uf13a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ShareApple = "\uf13a";

        /// <summary>
        /// fa-share-google unicode value ("\uf13b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ShareGoogle = "\uf13b";

        /// <summary>
        /// fa-spinner unicode value ("\uf13c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Spinner = "\uf13c";

        /// <summary>
        /// fa-spinner-2 unicode value ("\uf13d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Spinner2 = "\uf13d";

        /// <summary>
        /// fa-spinner-3 unicode value ("\uf13e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Spinner3 = "\uf13e";

        /// <summary>
        /// fa-star unicode value ("\uf13f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Star = "\uf13f";

        /// <summary>
        /// fa-tag unicode value ("\uf140").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Tag = "\uf140";

        /// <summary>
        /// fa-trash unicode value ("\uf141").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Trash = "\uf141";

        /// <summary>
        /// fa-trophy unicode value ("\uf142").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Trophy = "\uf142";

        /// <summary>
        /// fa-undo unicode value ("\uf143").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Undo = "\uf143";

        /// <summary>
        /// fa-unlock unicode value ("\uf144").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Unlock = "\uf144";

        /// <summary>
        /// fa-user unicode value ("\uf145").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string User = "\uf145";
    }
}
