using System;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by GlyphJsonToCsharp.
    /// </summary>
    public static partial class FeatherFont
    {
        /// <summary>
        /// fa-activity unicode value ("\uf100").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Activity = "\uf100";

        /// <summary>
        /// fa-airplay unicode value ("\uf101").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Airplay = "\uf101";

        /// <summary>
        /// fa-alert-circle unicode value ("\uf102").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AlertCircle = "\uf102";

        /// <summary>
        /// fa-alert-octagon unicode value ("\uf103").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AlertOctagon = "\uf103";

        /// <summary>
        /// fa-alert-triangle unicode value ("\uf104").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AlertTriangle = "\uf104";

        /// <summary>
        /// fa-align-center unicode value ("\uf105").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AlignCenter = "\uf105";

        /// <summary>
        /// fa-align-justify unicode value ("\uf106").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AlignJustify = "\uf106";

        /// <summary>
        /// fa-align-left unicode value ("\uf107").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AlignLeft = "\uf107";

        /// <summary>
        /// fa-align-right unicode value ("\uf108").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AlignRight = "\uf108";

        /// <summary>
        /// fa-anchor unicode value ("\uf109").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Anchor = "\uf109";

        /// <summary>
        /// fa-aperture unicode value ("\uf10a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Aperture = "\uf10a";

        /// <summary>
        /// fa-archive unicode value ("\uf10b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Archive = "\uf10b";

        /// <summary>
        /// fa-arrow-down unicode value ("\uf10c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowDown = "\uf10c";

        /// <summary>
        /// fa-arrow-down-circle unicode value ("\uf10d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowDownCircle = "\uf10d";

        /// <summary>
        /// fa-arrow-down-left unicode value ("\uf10e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowDownLeft = "\uf10e";

        /// <summary>
        /// fa-arrow-down-right unicode value ("\uf10f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowDownRight = "\uf10f";

        /// <summary>
        /// fa-arrow-left unicode value ("\uf110").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowLeft = "\uf110";

        /// <summary>
        /// fa-arrow-left-circle unicode value ("\uf111").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowLeftCircle = "\uf111";

        /// <summary>
        /// fa-arrow-right unicode value ("\uf112").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowRight = "\uf112";

        /// <summary>
        /// fa-arrow-right-circle unicode value ("\uf113").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowRightCircle = "\uf113";

        /// <summary>
        /// fa-arrow-up unicode value ("\uf114").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowUp = "\uf114";

        /// <summary>
        /// fa-arrow-up-circle unicode value ("\uf115").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowUpCircle = "\uf115";

        /// <summary>
        /// fa-arrow-up-left unicode value ("\uf116").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowUpLeft = "\uf116";

        /// <summary>
        /// fa-arrow-up-right unicode value ("\uf117").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowUpRight = "\uf117";

        /// <summary>
        /// fa-at-sign unicode value ("\uf118").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AtSign = "\uf118";

        /// <summary>
        /// fa-award unicode value ("\uf119").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Award = "\uf119";

        /// <summary>
        /// fa-bar-chart unicode value ("\uf11a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string BarChart = "\uf11a";

        /// <summary>
        /// fa-bar-chart-2 unicode value ("\uf11b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string BarChart2 = "\uf11b";

        /// <summary>
        /// fa-battery unicode value ("\uf11c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Battery = "\uf11c";

        /// <summary>
        /// fa-battery-charging unicode value ("\uf11d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string BatteryCharging = "\uf11d";

        /// <summary>
        /// fa-bell unicode value ("\uf11e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bell = "\uf11e";

        /// <summary>
        /// fa-bell-off unicode value ("\uf11f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string BellOff = "\uf11f";

        /// <summary>
        /// fa-bluetooth unicode value ("\uf120").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bluetooth = "\uf120";

        /// <summary>
        /// fa-bold unicode value ("\uf121").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bold = "\uf121";

        /// <summary>
        /// fa-book unicode value ("\uf122").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Book = "\uf122";

        /// <summary>
        /// fa-book-open unicode value ("\uf123").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string BookOpen = "\uf123";

        /// <summary>
        /// fa-bookmark unicode value ("\uf124").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bookmark = "\uf124";

        /// <summary>
        /// fa-box unicode value ("\uf125").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Box = "\uf125";

        /// <summary>
        /// fa-briefcase unicode value ("\uf126").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Briefcase = "\uf126";

        /// <summary>
        /// fa-calendar unicode value ("\uf127").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Calendar = "\uf127";

        /// <summary>
        /// fa-camera unicode value ("\uf128").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Camera = "\uf128";

        /// <summary>
        /// fa-camera-off unicode value ("\uf129").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CameraOff = "\uf129";

        /// <summary>
        /// fa-cast unicode value ("\uf12a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Cast = "\uf12a";

        /// <summary>
        /// fa-check unicode value ("\uf12b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Check = "\uf12b";

        /// <summary>
        /// fa-check-circle unicode value ("\uf12c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CheckCircle = "\uf12c";

        /// <summary>
        /// fa-check-square unicode value ("\uf12d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CheckSquare = "\uf12d";

        /// <summary>
        /// fa-chevron-down unicode value ("\uf12e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ChevronDown = "\uf12e";

        /// <summary>
        /// fa-chevron-left unicode value ("\uf12f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ChevronLeft = "\uf12f";

        /// <summary>
        /// fa-chevron-right unicode value ("\uf130").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ChevronRight = "\uf130";

        /// <summary>
        /// fa-chevron-up unicode value ("\uf131").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ChevronUp = "\uf131";

        /// <summary>
        /// fa-chevrons-down unicode value ("\uf132").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ChevronsDown = "\uf132";

        /// <summary>
        /// fa-chevrons-left unicode value ("\uf133").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ChevronsLeft = "\uf133";

        /// <summary>
        /// fa-chevrons-right unicode value ("\uf134").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ChevronsRight = "\uf134";

        /// <summary>
        /// fa-chevrons-up unicode value ("\uf135").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ChevronsUp = "\uf135";

        /// <summary>
        /// fa-chrome unicode value ("\uf136").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Chrome = "\uf136";

        /// <summary>
        /// fa-circle unicode value ("\uf137").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Circle = "\uf137";

        /// <summary>
        /// fa-clipboard unicode value ("\uf138").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Clipboard = "\uf138";

        /// <summary>
        /// fa-clock unicode value ("\uf139").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Clock = "\uf139";

        /// <summary>
        /// fa-cloud unicode value ("\uf13a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Cloud = "\uf13a";

        /// <summary>
        /// fa-cloud-drizzle unicode value ("\uf13b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CloudDrizzle = "\uf13b";

        /// <summary>
        /// fa-cloud-lightning unicode value ("\uf13c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CloudLightning = "\uf13c";

        /// <summary>
        /// fa-cloud-off unicode value ("\uf13d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CloudOff = "\uf13d";

        /// <summary>
        /// fa-cloud-rain unicode value ("\uf13e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CloudRain = "\uf13e";

        /// <summary>
        /// fa-cloud-snow unicode value ("\uf13f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CloudSnow = "\uf13f";

        /// <summary>
        /// fa-code unicode value ("\uf140").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Code = "\uf140";

        /// <summary>
        /// fa-codepen unicode value ("\uf141").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Codepen = "\uf141";

        /// <summary>
        /// fa-codesandbox unicode value ("\uf142").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Codesandbox = "\uf142";

        /// <summary>
        /// fa-coffee unicode value ("\uf143").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Coffee = "\uf143";

        /// <summary>
        /// fa-columns unicode value ("\uf144").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Columns = "\uf144";

        /// <summary>
        /// fa-command unicode value ("\uf145").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Command = "\uf145";

        /// <summary>
        /// fa-compass unicode value ("\uf146").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Compass = "\uf146";

        /// <summary>
        /// fa-copy unicode value ("\uf147").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Copy = "\uf147";

        /// <summary>
        /// fa-corner-down-left unicode value ("\uf148").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CornerDownLeft = "\uf148";

        /// <summary>
        /// fa-corner-down-right unicode value ("\uf149").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CornerDownRight = "\uf149";

        /// <summary>
        /// fa-corner-left-down unicode value ("\uf14a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CornerLeftDown = "\uf14a";

        /// <summary>
        /// fa-corner-left-up unicode value ("\uf14b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CornerLeftUp = "\uf14b";

        /// <summary>
        /// fa-corner-right-down unicode value ("\uf14c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CornerRightDown = "\uf14c";

        /// <summary>
        /// fa-corner-right-up unicode value ("\uf14d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CornerRightUp = "\uf14d";

        /// <summary>
        /// fa-corner-up-left unicode value ("\uf14e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CornerUpLeft = "\uf14e";

        /// <summary>
        /// fa-corner-up-right unicode value ("\uf14f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CornerUpRight = "\uf14f";

        /// <summary>
        /// fa-cpu unicode value ("\uf150").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Cpu = "\uf150";

        /// <summary>
        /// fa-credit-card unicode value ("\uf151").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CreditCard = "\uf151";

        /// <summary>
        /// fa-crop unicode value ("\uf152").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Crop = "\uf152";

        /// <summary>
        /// fa-crosshair unicode value ("\uf153").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Crosshair = "\uf153";

        /// <summary>
        /// fa-database unicode value ("\uf154").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Database = "\uf154";

        /// <summary>
        /// fa-delete unicode value ("\uf155").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Delete = "\uf155";

        /// <summary>
        /// fa-disc unicode value ("\uf156").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Disc = "\uf156";

        /// <summary>
        /// fa-divide unicode value ("\uf157").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Divide = "\uf157";

        /// <summary>
        /// fa-divide-circle unicode value ("\uf158").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DivideCircle = "\uf158";

        /// <summary>
        /// fa-divide-square unicode value ("\uf159").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DivideSquare = "\uf159";

        /// <summary>
        /// fa-dollar-sign unicode value ("\uf15a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DollarSign = "\uf15a";

        /// <summary>
        /// fa-download unicode value ("\uf15b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Download = "\uf15b";

        /// <summary>
        /// fa-download-cloud unicode value ("\uf15c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DownloadCloud = "\uf15c";

        /// <summary>
        /// fa-dribbble unicode value ("\uf15d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Dribbble = "\uf15d";

        /// <summary>
        /// fa-droplet unicode value ("\uf15e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Droplet = "\uf15e";

        /// <summary>
        /// fa-edit unicode value ("\uf15f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Edit = "\uf15f";

        /// <summary>
        /// fa-edit-2 unicode value ("\uf160").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Edit2 = "\uf160";

        /// <summary>
        /// fa-edit-3 unicode value ("\uf161").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Edit3 = "\uf161";

        /// <summary>
        /// fa-external-link unicode value ("\uf162").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ExternalLink = "\uf162";

        /// <summary>
        /// fa-eye unicode value ("\uf163").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Eye = "\uf163";

        /// <summary>
        /// fa-eye-off unicode value ("\uf164").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string EyeOff = "\uf164";

        /// <summary>
        /// fa-facebook unicode value ("\uf165").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Facebook = "\uf165";

        /// <summary>
        /// fa-fast-forward unicode value ("\uf166").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FastForward = "\uf166";

        /// <summary>
        /// fa-feather unicode value ("\uf167").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Feather = "\uf167";

        /// <summary>
        /// fa-figma unicode value ("\uf168").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Figma = "\uf168";

        /// <summary>
        /// fa-file unicode value ("\uf169").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string File = "\uf169";

        /// <summary>
        /// fa-file-minus unicode value ("\uf16a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FileMinus = "\uf16a";

        /// <summary>
        /// fa-file-plus unicode value ("\uf16b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FilePlus = "\uf16b";

        /// <summary>
        /// fa-file-text unicode value ("\uf16c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FileText = "\uf16c";

        /// <summary>
        /// fa-film unicode value ("\uf16d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Film = "\uf16d";

        /// <summary>
        /// fa-filter unicode value ("\uf16e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Filter = "\uf16e";

        /// <summary>
        /// fa-flag unicode value ("\uf16f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Flag = "\uf16f";

        /// <summary>
        /// fa-folder unicode value ("\uf170").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Folder = "\uf170";

        /// <summary>
        /// fa-folder-minus unicode value ("\uf171").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FolderMinus = "\uf171";

        /// <summary>
        /// fa-folder-plus unicode value ("\uf172").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FolderPlus = "\uf172";

        /// <summary>
        /// fa-framer unicode value ("\uf173").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Framer = "\uf173";

        /// <summary>
        /// fa-frown unicode value ("\uf174").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Frown = "\uf174";

        /// <summary>
        /// fa-gift unicode value ("\uf175").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Gift = "\uf175";

        /// <summary>
        /// fa-git-branch unicode value ("\uf176").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GitBranch = "\uf176";

        /// <summary>
        /// fa-git-commit unicode value ("\uf177").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GitCommit = "\uf177";

        /// <summary>
        /// fa-git-merge unicode value ("\uf178").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GitMerge = "\uf178";

        /// <summary>
        /// fa-git-pull-request unicode value ("\uf179").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GitPullRequest = "\uf179";

        /// <summary>
        /// fa-github unicode value ("\uf17a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Github = "\uf17a";

        /// <summary>
        /// fa-gitlab unicode value ("\uf17b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Gitlab = "\uf17b";

        /// <summary>
        /// fa-globe unicode value ("\uf17c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Globe = "\uf17c";

        /// <summary>
        /// fa-grid unicode value ("\uf17d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Grid = "\uf17d";

        /// <summary>
        /// fa-hard-drive unicode value ("\uf17e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string HardDrive = "\uf17e";

        /// <summary>
        /// fa-hash unicode value ("\uf17f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Hash = "\uf17f";

        /// <summary>
        /// fa-headphones unicode value ("\uf180").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Headphones = "\uf180";

        /// <summary>
        /// fa-heart unicode value ("\uf181").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Heart = "\uf181";

        /// <summary>
        /// fa-help-circle unicode value ("\uf182").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string HelpCircle = "\uf182";

        /// <summary>
        /// fa-hexagon unicode value ("\uf183").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Hexagon = "\uf183";

        /// <summary>
        /// fa-home unicode value ("\uf184").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Home = "\uf184";

        /// <summary>
        /// fa-image unicode value ("\uf185").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Image = "\uf185";

        /// <summary>
        /// fa-inbox unicode value ("\uf186").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Inbox = "\uf186";

        /// <summary>
        /// fa-info unicode value ("\uf187").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Info = "\uf187";

        /// <summary>
        /// fa-instagram unicode value ("\uf188").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Instagram = "\uf188";

        /// <summary>
        /// fa-italic unicode value ("\uf189").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Italic = "\uf189";

        /// <summary>
        /// fa-key unicode value ("\uf18a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Key = "\uf18a";

        /// <summary>
        /// fa-layers unicode value ("\uf18b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Layers = "\uf18b";

        /// <summary>
        /// fa-layout unicode value ("\uf18c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Layout = "\uf18c";

        /// <summary>
        /// fa-life-buoy unicode value ("\uf18d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string LifeBuoy = "\uf18d";

        /// <summary>
        /// fa-link unicode value ("\uf18e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Link = "\uf18e";

        /// <summary>
        /// fa-link-2 unicode value ("\uf18f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Link2 = "\uf18f";

        /// <summary>
        /// fa-linkedin unicode value ("\uf190").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Linkedin = "\uf190";

        /// <summary>
        /// fa-list unicode value ("\uf191").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string List = "\uf191";

        /// <summary>
        /// fa-loader unicode value ("\uf192").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Loader = "\uf192";

        /// <summary>
        /// fa-lock unicode value ("\uf193").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Lock = "\uf193";

        /// <summary>
        /// fa-log-in unicode value ("\uf194").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string LogIn = "\uf194";

        /// <summary>
        /// fa-log-out unicode value ("\uf195").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string LogOut = "\uf195";

        /// <summary>
        /// fa-mail unicode value ("\uf196").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Mail = "\uf196";

        /// <summary>
        /// fa-map unicode value ("\uf197").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Map = "\uf197";

        /// <summary>
        /// fa-map-pin unicode value ("\uf198").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MapPin = "\uf198";

        /// <summary>
        /// fa-maximize unicode value ("\uf199").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Maximize = "\uf199";

        /// <summary>
        /// fa-maximize-2 unicode value ("\uf19a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Maximize2 = "\uf19a";

        /// <summary>
        /// fa-meh unicode value ("\uf19b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Meh = "\uf19b";

        /// <summary>
        /// fa-menu unicode value ("\uf19c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Menu = "\uf19c";

        /// <summary>
        /// fa-message-circle unicode value ("\uf19d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MessageCircle = "\uf19d";

        /// <summary>
        /// fa-message-square unicode value ("\uf19e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MessageSquare = "\uf19e";

        /// <summary>
        /// fa-mic unicode value ("\uf19f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Mic = "\uf19f";

        /// <summary>
        /// fa-mic-off unicode value ("\uf1a0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MicOff = "\uf1a0";

        /// <summary>
        /// fa-minimize unicode value ("\uf1a1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Minimize = "\uf1a1";

        /// <summary>
        /// fa-minimize-2 unicode value ("\uf1a2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Minimize2 = "\uf1a2";

        /// <summary>
        /// fa-minus unicode value ("\uf1a3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Minus = "\uf1a3";

        /// <summary>
        /// fa-minus-circle unicode value ("\uf1a4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MinusCircle = "\uf1a4";

        /// <summary>
        /// fa-minus-square unicode value ("\uf1a5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MinusSquare = "\uf1a5";

        /// <summary>
        /// fa-monitor unicode value ("\uf1a6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Monitor = "\uf1a6";

        /// <summary>
        /// fa-moon unicode value ("\uf1a7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Moon = "\uf1a7";

        /// <summary>
        /// fa-more-horizontal unicode value ("\uf1a8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MoreHorizontal = "\uf1a8";

        /// <summary>
        /// fa-more-vertical unicode value ("\uf1a9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MoreVertical = "\uf1a9";

        /// <summary>
        /// fa-mouse-pointer unicode value ("\uf1aa").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MousePointer = "\uf1aa";

        /// <summary>
        /// fa-move unicode value ("\uf1ab").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Move = "\uf1ab";

        /// <summary>
        /// fa-music unicode value ("\uf1ac").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Music = "\uf1ac";

        /// <summary>
        /// fa-navigation unicode value ("\uf1ad").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Navigation = "\uf1ad";

        /// <summary>
        /// fa-navigation-2 unicode value ("\uf1ae").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Navigation2 = "\uf1ae";

        /// <summary>
        /// fa-octagon unicode value ("\uf1af").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Octagon = "\uf1af";

        /// <summary>
        /// fa-package unicode value ("\uf1b0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Package = "\uf1b0";

        /// <summary>
        /// fa-paperclip unicode value ("\uf1b1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Paperclip = "\uf1b1";

        /// <summary>
        /// fa-pause unicode value ("\uf1b2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pause = "\uf1b2";

        /// <summary>
        /// fa-pause-circle unicode value ("\uf1b3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PauseCircle = "\uf1b3";

        /// <summary>
        /// fa-pen-tool unicode value ("\uf1b4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PenTool = "\uf1b4";

        /// <summary>
        /// fa-percent unicode value ("\uf1b5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Percent = "\uf1b5";

        /// <summary>
        /// fa-phone unicode value ("\uf1b6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Phone = "\uf1b6";

        /// <summary>
        /// fa-phone-call unicode value ("\uf1b7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PhoneCall = "\uf1b7";

        /// <summary>
        /// fa-phone-forwarded unicode value ("\uf1b8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PhoneForwarded = "\uf1b8";

        /// <summary>
        /// fa-phone-incoming unicode value ("\uf1b9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PhoneIncoming = "\uf1b9";

        /// <summary>
        /// fa-phone-missed unicode value ("\uf1ba").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PhoneMissed = "\uf1ba";

        /// <summary>
        /// fa-phone-off unicode value ("\uf1bb").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PhoneOff = "\uf1bb";

        /// <summary>
        /// fa-phone-outgoing unicode value ("\uf1bc").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PhoneOutgoing = "\uf1bc";

        /// <summary>
        /// fa-pie-chart unicode value ("\uf1bd").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PieChart = "\uf1bd";

        /// <summary>
        /// fa-play unicode value ("\uf1be").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Play = "\uf1be";

        /// <summary>
        /// fa-play-circle unicode value ("\uf1bf").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PlayCircle = "\uf1bf";

        /// <summary>
        /// fa-plus unicode value ("\uf1c0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Plus = "\uf1c0";

        /// <summary>
        /// fa-plus-circle unicode value ("\uf1c1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PlusCircle = "\uf1c1";

        /// <summary>
        /// fa-plus-square unicode value ("\uf1c2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PlusSquare = "\uf1c2";

        /// <summary>
        /// fa-pocket unicode value ("\uf1c3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pocket = "\uf1c3";

        /// <summary>
        /// fa-power unicode value ("\uf1c4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Power = "\uf1c4";

        /// <summary>
        /// fa-printer unicode value ("\uf1c5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Printer = "\uf1c5";

        /// <summary>
        /// fa-radio unicode value ("\uf1c6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Radio = "\uf1c6";

        /// <summary>
        /// fa-refresh-ccw unicode value ("\uf1c7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string RefreshCcw = "\uf1c7";

        /// <summary>
        /// fa-refresh-cw unicode value ("\uf1c8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string RefreshCw = "\uf1c8";

        /// <summary>
        /// fa-repeat unicode value ("\uf1c9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Repeat = "\uf1c9";

        /// <summary>
        /// fa-rewind unicode value ("\uf1ca").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Rewind = "\uf1ca";

        /// <summary>
        /// fa-rotate-ccw unicode value ("\uf1cb").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string RotateCcw = "\uf1cb";

        /// <summary>
        /// fa-rotate-cw unicode value ("\uf1cc").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string RotateCw = "\uf1cc";

        /// <summary>
        /// fa-rss unicode value ("\uf1cd").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Rss = "\uf1cd";

        /// <summary>
        /// fa-save unicode value ("\uf1ce").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Save = "\uf1ce";

        /// <summary>
        /// fa-scissors unicode value ("\uf1cf").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Scissors = "\uf1cf";

        /// <summary>
        /// fa-search unicode value ("\uf1d0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Search = "\uf1d0";

        /// <summary>
        /// fa-send unicode value ("\uf1d1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Send = "\uf1d1";

        /// <summary>
        /// fa-server unicode value ("\uf1d2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Server = "\uf1d2";

        /// <summary>
        /// fa-settings unicode value ("\uf1d3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Settings = "\uf1d3";

        /// <summary>
        /// fa-share unicode value ("\uf1d4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Share = "\uf1d4";

        /// <summary>
        /// fa-share-2 unicode value ("\uf1d5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Share2 = "\uf1d5";

        /// <summary>
        /// fa-shield unicode value ("\uf1d6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Shield = "\uf1d6";

        /// <summary>
        /// fa-shield-off unicode value ("\uf1d7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ShieldOff = "\uf1d7";

        /// <summary>
        /// fa-shopping-bag unicode value ("\uf1d8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ShoppingBag = "\uf1d8";

        /// <summary>
        /// fa-shopping-cart unicode value ("\uf1d9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ShoppingCart = "\uf1d9";

        /// <summary>
        /// fa-shuffle unicode value ("\uf1da").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Shuffle = "\uf1da";

        /// <summary>
        /// fa-sidebar unicode value ("\uf1db").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Sidebar = "\uf1db";

        /// <summary>
        /// fa-skip-back unicode value ("\uf1dc").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SkipBack = "\uf1dc";

        /// <summary>
        /// fa-skip-forward unicode value ("\uf1dd").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SkipForward = "\uf1dd";

        /// <summary>
        /// fa-slack unicode value ("\uf1de").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Slack = "\uf1de";

        /// <summary>
        /// fa-slash unicode value ("\uf1df").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Slash = "\uf1df";

        /// <summary>
        /// fa-sliders unicode value ("\uf1e0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Sliders = "\uf1e0";

        /// <summary>
        /// fa-smartphone unicode value ("\uf1e1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Smartphone = "\uf1e1";

        /// <summary>
        /// fa-smile unicode value ("\uf1e2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Smile = "\uf1e2";

        /// <summary>
        /// fa-speaker unicode value ("\uf1e3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Speaker = "\uf1e3";

        /// <summary>
        /// fa-square unicode value ("\uf1e4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Square = "\uf1e4";

        /// <summary>
        /// fa-star unicode value ("\uf1e5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Star = "\uf1e5";

        /// <summary>
        /// fa-stop-circle unicode value ("\uf1e6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string StopCircle = "\uf1e6";

        /// <summary>
        /// fa-sun unicode value ("\uf1e7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Sun = "\uf1e7";

        /// <summary>
        /// fa-sunrise unicode value ("\uf1e8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Sunrise = "\uf1e8";

        /// <summary>
        /// fa-sunset unicode value ("\uf1e9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Sunset = "\uf1e9";

        /// <summary>
        /// fa-tablet unicode value ("\uf1ea").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Tablet = "\uf1ea";

        /// <summary>
        /// fa-tag unicode value ("\uf1eb").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Tag = "\uf1eb";

        /// <summary>
        /// fa-target unicode value ("\uf1ec").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Target = "\uf1ec";

        /// <summary>
        /// fa-terminal unicode value ("\uf1ed").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Terminal = "\uf1ed";

        /// <summary>
        /// fa-thermometer unicode value ("\uf1ee").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Thermometer = "\uf1ee";

        /// <summary>
        /// fa-thumbs-down unicode value ("\uf1ef").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ThumbsDown = "\uf1ef";

        /// <summary>
        /// fa-thumbs-up unicode value ("\uf1f0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ThumbsUp = "\uf1f0";

        /// <summary>
        /// fa-toggle-left unicode value ("\uf1f1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ToggleLeft = "\uf1f1";

        /// <summary>
        /// fa-toggle-right unicode value ("\uf1f2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ToggleRight = "\uf1f2";

        /// <summary>
        /// fa-tool unicode value ("\uf1f3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Tool = "\uf1f3";

        /// <summary>
        /// fa-trash unicode value ("\uf1f4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Trash = "\uf1f4";

        /// <summary>
        /// fa-trash-2 unicode value ("\uf1f5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Trash2 = "\uf1f5";

        /// <summary>
        /// fa-trello unicode value ("\uf1f6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Trello = "\uf1f6";

        /// <summary>
        /// fa-trending-down unicode value ("\uf1f7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TrendingDown = "\uf1f7";

        /// <summary>
        /// fa-trending-up unicode value ("\uf1f8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TrendingUp = "\uf1f8";

        /// <summary>
        /// fa-triangle unicode value ("\uf1f9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Triangle = "\uf1f9";

        /// <summary>
        /// fa-truck unicode value ("\uf1fa").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Truck = "\uf1fa";

        /// <summary>
        /// fa-tv unicode value ("\uf1fb").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Tv = "\uf1fb";

        /// <summary>
        /// fa-twitch unicode value ("\uf1fc").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Twitch = "\uf1fc";

        /// <summary>
        /// fa-twitter unicode value ("\uf1fd").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Twitter = "\uf1fd";

        /// <summary>
        /// fa-type unicode value ("\uf1fe").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Type = "\uf1fe";

        /// <summary>
        /// fa-umbrella unicode value ("\uf1ff").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Umbrella = "\uf1ff";

        /// <summary>
        /// fa-underline unicode value ("\uf200").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Underline = "\uf200";

        /// <summary>
        /// fa-unlock unicode value ("\uf201").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Unlock = "\uf201";

        /// <summary>
        /// fa-upload unicode value ("\uf202").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Upload = "\uf202";

        /// <summary>
        /// fa-upload-cloud unicode value ("\uf203").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string UploadCloud = "\uf203";

        /// <summary>
        /// fa-user unicode value ("\uf204").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string User = "\uf204";

        /// <summary>
        /// fa-user-check unicode value ("\uf205").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string UserCheck = "\uf205";

        /// <summary>
        /// fa-user-minus unicode value ("\uf206").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string UserMinus = "\uf206";

        /// <summary>
        /// fa-user-plus unicode value ("\uf207").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string UserPlus = "\uf207";

        /// <summary>
        /// fa-user-x unicode value ("\uf208").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string UserX = "\uf208";

        /// <summary>
        /// fa-users unicode value ("\uf209").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Users = "\uf209";

        /// <summary>
        /// fa-video unicode value ("\uf20a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Video = "\uf20a";

        /// <summary>
        /// fa-video-off unicode value ("\uf20b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string VideoOff = "\uf20b";

        /// <summary>
        /// fa-voicemail unicode value ("\uf20c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Voicemail = "\uf20c";

        /// <summary>
        /// fa-volume unicode value ("\uf20d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Volume = "\uf20d";

        /// <summary>
        /// fa-volume-1 unicode value ("\uf20e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Volume1 = "\uf20e";

        /// <summary>
        /// fa-volume-2 unicode value ("\uf20f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Volume2 = "\uf20f";

        /// <summary>
        /// fa-volume-x unicode value ("\uf210").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string VolumeX = "\uf210";

        /// <summary>
        /// fa-watch unicode value ("\uf211").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Watch = "\uf211";

        /// <summary>
        /// fa-wifi unicode value ("\uf212").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Wifi = "\uf212";

        /// <summary>
        /// fa-wifi-off unicode value ("\uf213").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string WifiOff = "\uf213";

        /// <summary>
        /// fa-wind unicode value ("\uf214").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Wind = "\uf214";

        /// <summary>
        /// fa-x unicode value ("\uf215").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string X = "\uf215";

        /// <summary>
        /// fa-x-circle unicode value ("\uf216").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string XCircle = "\uf216";

        /// <summary>
        /// fa-x-octagon unicode value ("\uf217").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string XOctagon = "\uf217";

        /// <summary>
        /// fa-x-square unicode value ("\uf218").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string XSquare = "\uf218";

        /// <summary>
        /// fa-youtube unicode value ("\uf219").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Youtube = "\uf219";

        /// <summary>
        /// fa-zap unicode value ("\uf21a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Zap = "\uf21a";

        /// <summary>
        /// fa-zap-off unicode value ("\uf21b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ZapOff = "\uf21b";

        /// <summary>
        /// fa-zoom-in unicode value ("\uf21c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ZoomIn = "\uf21c";

        /// <summary>
        /// fa-zoom-out unicode value ("\uf21d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ZoomOut = "\uf21d";
    }
}
