using System;

namespace VectorIcons
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by GlyphJsonToCsharp.
    /// </summary>
    public static partial class FoundationFont
    {
        /// <summary>
        /// fa-address-book unicode value ("\uf100").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AddressBook = "\uf100";

        /// <summary>
        /// fa-alert unicode value ("\uf101").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Alert = "\uf101";

        /// <summary>
        /// fa-align-center unicode value ("\uf102").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AlignCenter = "\uf102";

        /// <summary>
        /// fa-align-justify unicode value ("\uf103").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AlignJustify = "\uf103";

        /// <summary>
        /// fa-align-left unicode value ("\uf104").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AlignLeft = "\uf104";

        /// <summary>
        /// fa-align-right unicode value ("\uf105").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AlignRight = "\uf105";

        /// <summary>
        /// fa-anchor unicode value ("\uf106").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Anchor = "\uf106";

        /// <summary>
        /// fa-annotate unicode value ("\uf107").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Annotate = "\uf107";

        /// <summary>
        /// fa-archive unicode value ("\uf108").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Archive = "\uf108";

        /// <summary>
        /// fa-arrow-down unicode value ("\uf109").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowDown = "\uf109";

        /// <summary>
        /// fa-arrow-left unicode value ("\uf10a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowLeft = "\uf10a";

        /// <summary>
        /// fa-arrow-right unicode value ("\uf10b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowRight = "\uf10b";

        /// <summary>
        /// fa-arrow-up unicode value ("\uf10c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowUp = "\uf10c";

        /// <summary>
        /// fa-arrows-compress unicode value ("\uf10d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowsCompress = "\uf10d";

        /// <summary>
        /// fa-arrows-expand unicode value ("\uf10e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowsExpand = "\uf10e";

        /// <summary>
        /// fa-arrows-in unicode value ("\uf10f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowsIn = "\uf10f";

        /// <summary>
        /// fa-arrows-out unicode value ("\uf110").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowsOut = "\uf110";

        /// <summary>
        /// fa-asl unicode value ("\uf111").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Asl = "\uf111";

        /// <summary>
        /// fa-asterisk unicode value ("\uf112").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Asterisk = "\uf112";

        /// <summary>
        /// fa-at-sign unicode value ("\uf113").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string AtSign = "\uf113";

        /// <summary>
        /// fa-background-color unicode value ("\uf114").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string BackgroundColor = "\uf114";

        /// <summary>
        /// fa-battery-empty unicode value ("\uf115").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string BatteryEmpty = "\uf115";

        /// <summary>
        /// fa-battery-full unicode value ("\uf116").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string BatteryFull = "\uf116";

        /// <summary>
        /// fa-battery-half unicode value ("\uf117").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string BatteryHalf = "\uf117";

        /// <summary>
        /// fa-bitcoin-circle unicode value ("\uf118").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string BitcoinCircle = "\uf118";

        /// <summary>
        /// fa-bitcoin unicode value ("\uf119").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bitcoin = "\uf119";

        /// <summary>
        /// fa-blind unicode value ("\uf11a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Blind = "\uf11a";

        /// <summary>
        /// fa-bluetooth unicode value ("\uf11b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bluetooth = "\uf11b";

        /// <summary>
        /// fa-bold unicode value ("\uf11c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bold = "\uf11c";

        /// <summary>
        /// fa-book-bookmark unicode value ("\uf11d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string BookBookmark = "\uf11d";

        /// <summary>
        /// fa-book unicode value ("\uf11e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Book = "\uf11e";

        /// <summary>
        /// fa-bookmark unicode value ("\uf11f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bookmark = "\uf11f";

        /// <summary>
        /// fa-braille unicode value ("\uf120").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Braille = "\uf120";

        /// <summary>
        /// fa-burst-new unicode value ("\uf121").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string BurstNew = "\uf121";

        /// <summary>
        /// fa-burst-sale unicode value ("\uf122").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string BurstSale = "\uf122";

        /// <summary>
        /// fa-burst unicode value ("\uf123").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Burst = "\uf123";

        /// <summary>
        /// fa-calendar unicode value ("\uf124").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Calendar = "\uf124";

        /// <summary>
        /// fa-camera unicode value ("\uf125").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Camera = "\uf125";

        /// <summary>
        /// fa-check unicode value ("\uf126").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Check = "\uf126";

        /// <summary>
        /// fa-checkbox unicode value ("\uf127").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Checkbox = "\uf127";

        /// <summary>
        /// fa-clipboard-notes unicode value ("\uf128").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ClipboardNotes = "\uf128";

        /// <summary>
        /// fa-clipboard-pencil unicode value ("\uf129").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ClipboardPencil = "\uf129";

        /// <summary>
        /// fa-clipboard unicode value ("\uf12a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Clipboard = "\uf12a";

        /// <summary>
        /// fa-clock unicode value ("\uf12b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Clock = "\uf12b";

        /// <summary>
        /// fa-closed-caption unicode value ("\uf12c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ClosedCaption = "\uf12c";

        /// <summary>
        /// fa-cloud unicode value ("\uf12d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Cloud = "\uf12d";

        /// <summary>
        /// fa-comment-minus unicode value ("\uf12e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CommentMinus = "\uf12e";

        /// <summary>
        /// fa-comment-quotes unicode value ("\uf12f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CommentQuotes = "\uf12f";

        /// <summary>
        /// fa-comment-video unicode value ("\uf130").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CommentVideo = "\uf130";

        /// <summary>
        /// fa-comment unicode value ("\uf131").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Comment = "\uf131";

        /// <summary>
        /// fa-comments unicode value ("\uf132").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Comments = "\uf132";

        /// <summary>
        /// fa-compass unicode value ("\uf133").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Compass = "\uf133";

        /// <summary>
        /// fa-contrast unicode value ("\uf134").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Contrast = "\uf134";

        /// <summary>
        /// fa-credit-card unicode value ("\uf135").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CreditCard = "\uf135";

        /// <summary>
        /// fa-crop unicode value ("\uf136").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Crop = "\uf136";

        /// <summary>
        /// fa-crown unicode value ("\uf137").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Crown = "\uf137";

        /// <summary>
        /// fa-css3 unicode value ("\uf138").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Css3 = "\uf138";

        /// <summary>
        /// fa-database unicode value ("\uf139").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Database = "\uf139";

        /// <summary>
        /// fa-die-five unicode value ("\uf13a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DieFive = "\uf13a";

        /// <summary>
        /// fa-die-four unicode value ("\uf13b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DieFour = "\uf13b";

        /// <summary>
        /// fa-die-one unicode value ("\uf13c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DieOne = "\uf13c";

        /// <summary>
        /// fa-die-six unicode value ("\uf13d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DieSix = "\uf13d";

        /// <summary>
        /// fa-die-three unicode value ("\uf13e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DieThree = "\uf13e";

        /// <summary>
        /// fa-die-two unicode value ("\uf13f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DieTwo = "\uf13f";

        /// <summary>
        /// fa-dislike unicode value ("\uf140").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Dislike = "\uf140";

        /// <summary>
        /// fa-dollar-bill unicode value ("\uf141").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DollarBill = "\uf141";

        /// <summary>
        /// fa-dollar unicode value ("\uf142").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Dollar = "\uf142";

        /// <summary>
        /// fa-download unicode value ("\uf143").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Download = "\uf143";

        /// <summary>
        /// fa-eject unicode value ("\uf144").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Eject = "\uf144";

        /// <summary>
        /// fa-elevator unicode value ("\uf145").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Elevator = "\uf145";

        /// <summary>
        /// fa-euro unicode value ("\uf146").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Euro = "\uf146";

        /// <summary>
        /// fa-eye unicode value ("\uf147").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Eye = "\uf147";

        /// <summary>
        /// fa-fast-forward unicode value ("\uf148").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FastForward = "\uf148";

        /// <summary>
        /// fa-female-symbol unicode value ("\uf149").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FemaleSymbol = "\uf149";

        /// <summary>
        /// fa-female unicode value ("\uf14a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Female = "\uf14a";

        /// <summary>
        /// fa-filter unicode value ("\uf14b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Filter = "\uf14b";

        /// <summary>
        /// fa-first-aid unicode value ("\uf14c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FirstAid = "\uf14c";

        /// <summary>
        /// fa-flag unicode value ("\uf14d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Flag = "\uf14d";

        /// <summary>
        /// fa-folder-add unicode value ("\uf14e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FolderAdd = "\uf14e";

        /// <summary>
        /// fa-folder-lock unicode value ("\uf14f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FolderLock = "\uf14f";

        /// <summary>
        /// fa-folder unicode value ("\uf150").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Folder = "\uf150";

        /// <summary>
        /// fa-foot unicode value ("\uf151").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Foot = "\uf151";

        /// <summary>
        /// fa-foundation unicode value ("\uf152").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Foundation = "\uf152";

        /// <summary>
        /// fa-graph-bar unicode value ("\uf153").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GraphBar = "\uf153";

        /// <summary>
        /// fa-graph-horizontal unicode value ("\uf154").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GraphHorizontal = "\uf154";

        /// <summary>
        /// fa-graph-pie unicode value ("\uf155").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GraphPie = "\uf155";

        /// <summary>
        /// fa-graph-trend unicode value ("\uf156").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GraphTrend = "\uf156";

        /// <summary>
        /// fa-guide-dog unicode value ("\uf157").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GuideDog = "\uf157";

        /// <summary>
        /// fa-hearing-aid unicode value ("\uf158").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string HearingAid = "\uf158";

        /// <summary>
        /// fa-heart unicode value ("\uf159").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Heart = "\uf159";

        /// <summary>
        /// fa-home unicode value ("\uf15a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Home = "\uf15a";

        /// <summary>
        /// fa-html5 unicode value ("\uf15b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Html5 = "\uf15b";

        /// <summary>
        /// fa-indent-less unicode value ("\uf15c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string IndentLess = "\uf15c";

        /// <summary>
        /// fa-indent-more unicode value ("\uf15d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string IndentMore = "\uf15d";

        /// <summary>
        /// fa-info unicode value ("\uf15e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Info = "\uf15e";

        /// <summary>
        /// fa-italic unicode value ("\uf15f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Italic = "\uf15f";

        /// <summary>
        /// fa-key unicode value ("\uf160").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Key = "\uf160";

        /// <summary>
        /// fa-laptop unicode value ("\uf161").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Laptop = "\uf161";

        /// <summary>
        /// fa-layout unicode value ("\uf162").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Layout = "\uf162";

        /// <summary>
        /// fa-lightbulb unicode value ("\uf163").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Lightbulb = "\uf163";

        /// <summary>
        /// fa-like unicode value ("\uf164").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Like = "\uf164";

        /// <summary>
        /// fa-link unicode value ("\uf165").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Link = "\uf165";

        /// <summary>
        /// fa-list-bullet unicode value ("\uf166").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ListBullet = "\uf166";

        /// <summary>
        /// fa-list-number unicode value ("\uf167").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ListNumber = "\uf167";

        /// <summary>
        /// fa-list-thumbnails unicode value ("\uf168").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ListThumbnails = "\uf168";

        /// <summary>
        /// fa-list unicode value ("\uf169").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string List = "\uf169";

        /// <summary>
        /// fa-lock unicode value ("\uf16a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Lock = "\uf16a";

        /// <summary>
        /// fa-loop unicode value ("\uf16b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Loop = "\uf16b";

        /// <summary>
        /// fa-magnifying-glass unicode value ("\uf16c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MagnifyingGlass = "\uf16c";

        /// <summary>
        /// fa-mail unicode value ("\uf16d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Mail = "\uf16d";

        /// <summary>
        /// fa-male-female unicode value ("\uf16e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MaleFemale = "\uf16e";

        /// <summary>
        /// fa-male-symbol unicode value ("\uf16f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MaleSymbol = "\uf16f";

        /// <summary>
        /// fa-male unicode value ("\uf170").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Male = "\uf170";

        /// <summary>
        /// fa-map unicode value ("\uf171").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Map = "\uf171";

        /// <summary>
        /// fa-marker unicode value ("\uf172").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Marker = "\uf172";

        /// <summary>
        /// fa-megaphone unicode value ("\uf173").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Megaphone = "\uf173";

        /// <summary>
        /// fa-microphone unicode value ("\uf174").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Microphone = "\uf174";

        /// <summary>
        /// fa-minus-circle unicode value ("\uf175").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MinusCircle = "\uf175";

        /// <summary>
        /// fa-minus unicode value ("\uf176").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Minus = "\uf176";

        /// <summary>
        /// fa-mobile-signal unicode value ("\uf177").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MobileSignal = "\uf177";

        /// <summary>
        /// fa-mobile unicode value ("\uf178").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Mobile = "\uf178";

        /// <summary>
        /// fa-monitor unicode value ("\uf179").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Monitor = "\uf179";

        /// <summary>
        /// fa-mountains unicode value ("\uf17a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Mountains = "\uf17a";

        /// <summary>
        /// fa-music unicode value ("\uf17b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Music = "\uf17b";

        /// <summary>
        /// fa-next unicode value ("\uf17c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Next = "\uf17c";

        /// <summary>
        /// fa-no-dogs unicode value ("\uf17d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string NoDogs = "\uf17d";

        /// <summary>
        /// fa-no-smoking unicode value ("\uf17e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string NoSmoking = "\uf17e";

        /// <summary>
        /// fa-page-add unicode value ("\uf17f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PageAdd = "\uf17f";

        /// <summary>
        /// fa-page-copy unicode value ("\uf180").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PageCopy = "\uf180";

        /// <summary>
        /// fa-page-csv unicode value ("\uf181").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PageCsv = "\uf181";

        /// <summary>
        /// fa-page-delete unicode value ("\uf182").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PageDelete = "\uf182";

        /// <summary>
        /// fa-page-doc unicode value ("\uf183").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PageDoc = "\uf183";

        /// <summary>
        /// fa-page-edit unicode value ("\uf184").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PageEdit = "\uf184";

        /// <summary>
        /// fa-page-export-csv unicode value ("\uf185").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PageExportCsv = "\uf185";

        /// <summary>
        /// fa-page-export-doc unicode value ("\uf186").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PageExportDoc = "\uf186";

        /// <summary>
        /// fa-page-export-pdf unicode value ("\uf187").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PageExportPdf = "\uf187";

        /// <summary>
        /// fa-page-export unicode value ("\uf188").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PageExport = "\uf188";

        /// <summary>
        /// fa-page-filled unicode value ("\uf189").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PageFilled = "\uf189";

        /// <summary>
        /// fa-page-multiple unicode value ("\uf18a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PageMultiple = "\uf18a";

        /// <summary>
        /// fa-page-pdf unicode value ("\uf18b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PagePdf = "\uf18b";

        /// <summary>
        /// fa-page-remove unicode value ("\uf18c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PageRemove = "\uf18c";

        /// <summary>
        /// fa-page-search unicode value ("\uf18d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PageSearch = "\uf18d";

        /// <summary>
        /// fa-page unicode value ("\uf18e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Page = "\uf18e";

        /// <summary>
        /// fa-paint-bucket unicode value ("\uf18f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PaintBucket = "\uf18f";

        /// <summary>
        /// fa-paperclip unicode value ("\uf190").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Paperclip = "\uf190";

        /// <summary>
        /// fa-pause unicode value ("\uf191").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pause = "\uf191";

        /// <summary>
        /// fa-paw unicode value ("\uf192").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Paw = "\uf192";

        /// <summary>
        /// fa-paypal unicode value ("\uf193").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Paypal = "\uf193";

        /// <summary>
        /// fa-pencil unicode value ("\uf194").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pencil = "\uf194";

        /// <summary>
        /// fa-photo unicode value ("\uf195").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Photo = "\uf195";

        /// <summary>
        /// fa-play-circle unicode value ("\uf196").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PlayCircle = "\uf196";

        /// <summary>
        /// fa-play-video unicode value ("\uf197").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PlayVideo = "\uf197";

        /// <summary>
        /// fa-play unicode value ("\uf198").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Play = "\uf198";

        /// <summary>
        /// fa-plus unicode value ("\uf199").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Plus = "\uf199";

        /// <summary>
        /// fa-pound unicode value ("\uf19a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pound = "\uf19a";

        /// <summary>
        /// fa-power unicode value ("\uf19b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Power = "\uf19b";

        /// <summary>
        /// fa-previous unicode value ("\uf19c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Previous = "\uf19c";

        /// <summary>
        /// fa-price-tag unicode value ("\uf19d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PriceTag = "\uf19d";

        /// <summary>
        /// fa-pricetag-multiple unicode value ("\uf19e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PricetagMultiple = "\uf19e";

        /// <summary>
        /// fa-print unicode value ("\uf19f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Print = "\uf19f";

        /// <summary>
        /// fa-prohibited unicode value ("\uf1a0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Prohibited = "\uf1a0";

        /// <summary>
        /// fa-projection-screen unicode value ("\uf1a1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ProjectionScreen = "\uf1a1";

        /// <summary>
        /// fa-puzzle unicode value ("\uf1a2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Puzzle = "\uf1a2";

        /// <summary>
        /// fa-quote unicode value ("\uf1a3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Quote = "\uf1a3";

        /// <summary>
        /// fa-record unicode value ("\uf1a4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Record = "\uf1a4";

        /// <summary>
        /// fa-refresh unicode value ("\uf1a5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Refresh = "\uf1a5";

        /// <summary>
        /// fa-results-demographics unicode value ("\uf1a6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ResultsDemographics = "\uf1a6";

        /// <summary>
        /// fa-results unicode value ("\uf1a7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Results = "\uf1a7";

        /// <summary>
        /// fa-rewind-ten unicode value ("\uf1a8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string RewindTen = "\uf1a8";

        /// <summary>
        /// fa-rewind unicode value ("\uf1a9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Rewind = "\uf1a9";

        /// <summary>
        /// fa-rss unicode value ("\uf1aa").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Rss = "\uf1aa";

        /// <summary>
        /// fa-safety-cone unicode value ("\uf1ab").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SafetyCone = "\uf1ab";

        /// <summary>
        /// fa-save unicode value ("\uf1ac").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Save = "\uf1ac";

        /// <summary>
        /// fa-share unicode value ("\uf1ad").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Share = "\uf1ad";

        /// <summary>
        /// fa-sheriff-badge unicode value ("\uf1ae").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SheriffBadge = "\uf1ae";

        /// <summary>
        /// fa-shield unicode value ("\uf1af").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Shield = "\uf1af";

        /// <summary>
        /// fa-shopping-bag unicode value ("\uf1b0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ShoppingBag = "\uf1b0";

        /// <summary>
        /// fa-shopping-cart unicode value ("\uf1b1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ShoppingCart = "\uf1b1";

        /// <summary>
        /// fa-shuffle unicode value ("\uf1b2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Shuffle = "\uf1b2";

        /// <summary>
        /// fa-skull unicode value ("\uf1b3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Skull = "\uf1b3";

        /// <summary>
        /// fa-social-500px unicode value ("\uf1b4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Social500px = "\uf1b4";

        /// <summary>
        /// fa-social-adobe unicode value ("\uf1b5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialAdobe = "\uf1b5";

        /// <summary>
        /// fa-social-amazon unicode value ("\uf1b6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialAmazon = "\uf1b6";

        /// <summary>
        /// fa-social-android unicode value ("\uf1b7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialAndroid = "\uf1b7";

        /// <summary>
        /// fa-social-apple unicode value ("\uf1b8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialApple = "\uf1b8";

        /// <summary>
        /// fa-social-behance unicode value ("\uf1b9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialBehance = "\uf1b9";

        /// <summary>
        /// fa-social-bing unicode value ("\uf1ba").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialBing = "\uf1ba";

        /// <summary>
        /// fa-social-blogger unicode value ("\uf1bb").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialBlogger = "\uf1bb";

        /// <summary>
        /// fa-social-delicious unicode value ("\uf1bc").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialDelicious = "\uf1bc";

        /// <summary>
        /// fa-social-designer-news unicode value ("\uf1bd").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialDesignerNews = "\uf1bd";

        /// <summary>
        /// fa-social-deviant-art unicode value ("\uf1be").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialDeviantArt = "\uf1be";

        /// <summary>
        /// fa-social-digg unicode value ("\uf1bf").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialDigg = "\uf1bf";

        /// <summary>
        /// fa-social-dribbble unicode value ("\uf1c0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialDribbble = "\uf1c0";

        /// <summary>
        /// fa-social-drive unicode value ("\uf1c1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialDrive = "\uf1c1";

        /// <summary>
        /// fa-social-dropbox unicode value ("\uf1c2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialDropbox = "\uf1c2";

        /// <summary>
        /// fa-social-evernote unicode value ("\uf1c3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialEvernote = "\uf1c3";

        /// <summary>
        /// fa-social-facebook unicode value ("\uf1c4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialFacebook = "\uf1c4";

        /// <summary>
        /// fa-social-flickr unicode value ("\uf1c5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialFlickr = "\uf1c5";

        /// <summary>
        /// fa-social-forrst unicode value ("\uf1c6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialForrst = "\uf1c6";

        /// <summary>
        /// fa-social-foursquare unicode value ("\uf1c7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialFoursquare = "\uf1c7";

        /// <summary>
        /// fa-social-game-center unicode value ("\uf1c8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialGameCenter = "\uf1c8";

        /// <summary>
        /// fa-social-github unicode value ("\uf1c9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialGithub = "\uf1c9";

        /// <summary>
        /// fa-social-google-plus unicode value ("\uf1ca").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialGooglePlus = "\uf1ca";

        /// <summary>
        /// fa-social-hacker-news unicode value ("\uf1cb").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialHackerNews = "\uf1cb";

        /// <summary>
        /// fa-social-hi5 unicode value ("\uf1cc").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialHi5 = "\uf1cc";

        /// <summary>
        /// fa-social-instagram unicode value ("\uf1cd").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialInstagram = "\uf1cd";

        /// <summary>
        /// fa-social-joomla unicode value ("\uf1ce").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialJoomla = "\uf1ce";

        /// <summary>
        /// fa-social-lastfm unicode value ("\uf1cf").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialLastfm = "\uf1cf";

        /// <summary>
        /// fa-social-linkedin unicode value ("\uf1d0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialLinkedin = "\uf1d0";

        /// <summary>
        /// fa-social-medium unicode value ("\uf1d1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialMedium = "\uf1d1";

        /// <summary>
        /// fa-social-myspace unicode value ("\uf1d2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialMyspace = "\uf1d2";

        /// <summary>
        /// fa-social-orkut unicode value ("\uf1d3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialOrkut = "\uf1d3";

        /// <summary>
        /// fa-social-path unicode value ("\uf1d4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialPath = "\uf1d4";

        /// <summary>
        /// fa-social-picasa unicode value ("\uf1d5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialPicasa = "\uf1d5";

        /// <summary>
        /// fa-social-pinterest unicode value ("\uf1d6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialPinterest = "\uf1d6";

        /// <summary>
        /// fa-social-rdio unicode value ("\uf1d7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialRdio = "\uf1d7";

        /// <summary>
        /// fa-social-reddit unicode value ("\uf1d8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialReddit = "\uf1d8";

        /// <summary>
        /// fa-social-skillshare unicode value ("\uf1d9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialSkillshare = "\uf1d9";

        /// <summary>
        /// fa-social-skype unicode value ("\uf1da").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialSkype = "\uf1da";

        /// <summary>
        /// fa-social-smashing-mag unicode value ("\uf1db").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialSmashingMag = "\uf1db";

        /// <summary>
        /// fa-social-snapchat unicode value ("\uf1dc").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialSnapchat = "\uf1dc";

        /// <summary>
        /// fa-social-spotify unicode value ("\uf1dd").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialSpotify = "\uf1dd";

        /// <summary>
        /// fa-social-squidoo unicode value ("\uf1de").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialSquidoo = "\uf1de";

        /// <summary>
        /// fa-social-stack-overflow unicode value ("\uf1df").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialStackOverflow = "\uf1df";

        /// <summary>
        /// fa-social-steam unicode value ("\uf1e0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialSteam = "\uf1e0";

        /// <summary>
        /// fa-social-stumbleupon unicode value ("\uf1e1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialStumbleupon = "\uf1e1";

        /// <summary>
        /// fa-social-treehouse unicode value ("\uf1e2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialTreehouse = "\uf1e2";

        /// <summary>
        /// fa-social-tumblr unicode value ("\uf1e3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialTumblr = "\uf1e3";

        /// <summary>
        /// fa-social-twitter unicode value ("\uf1e4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialTwitter = "\uf1e4";

        /// <summary>
        /// fa-social-vimeo unicode value ("\uf1e5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialVimeo = "\uf1e5";

        /// <summary>
        /// fa-social-windows unicode value ("\uf1e6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialWindows = "\uf1e6";

        /// <summary>
        /// fa-social-xbox unicode value ("\uf1e7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialXbox = "\uf1e7";

        /// <summary>
        /// fa-social-yahoo unicode value ("\uf1e8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialYahoo = "\uf1e8";

        /// <summary>
        /// fa-social-yelp unicode value ("\uf1e9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialYelp = "\uf1e9";

        /// <summary>
        /// fa-social-youtube unicode value ("\uf1ea").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialYoutube = "\uf1ea";

        /// <summary>
        /// fa-social-zerply unicode value ("\uf1eb").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialZerply = "\uf1eb";

        /// <summary>
        /// fa-social-zurb unicode value ("\uf1ec").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialZurb = "\uf1ec";

        /// <summary>
        /// fa-sound unicode value ("\uf1ed").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Sound = "\uf1ed";

        /// <summary>
        /// fa-star unicode value ("\uf1ee").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Star = "\uf1ee";

        /// <summary>
        /// fa-stop unicode value ("\uf1ef").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Stop = "\uf1ef";

        /// <summary>
        /// fa-strikethrough unicode value ("\uf1f0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Strikethrough = "\uf1f0";

        /// <summary>
        /// fa-subscript unicode value ("\uf1f1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Subscript = "\uf1f1";

        /// <summary>
        /// fa-superscript unicode value ("\uf1f2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Superscript = "\uf1f2";

        /// <summary>
        /// fa-tablet-landscape unicode value ("\uf1f3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TabletLandscape = "\uf1f3";

        /// <summary>
        /// fa-tablet-portrait unicode value ("\uf1f4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TabletPortrait = "\uf1f4";

        /// <summary>
        /// fa-target-two unicode value ("\uf1f5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TargetTwo = "\uf1f5";

        /// <summary>
        /// fa-target unicode value ("\uf1f6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Target = "\uf1f6";

        /// <summary>
        /// fa-telephone-accessible unicode value ("\uf1f7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TelephoneAccessible = "\uf1f7";

        /// <summary>
        /// fa-telephone unicode value ("\uf1f8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Telephone = "\uf1f8";

        /// <summary>
        /// fa-text-color unicode value ("\uf1f9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TextColor = "\uf1f9";

        /// <summary>
        /// fa-thumbnails unicode value ("\uf1fa").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Thumbnails = "\uf1fa";

        /// <summary>
        /// fa-ticket unicode value ("\uf1fb").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Ticket = "\uf1fb";

        /// <summary>
        /// fa-torso-business unicode value ("\uf1fc").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TorsoBusiness = "\uf1fc";

        /// <summary>
        /// fa-torso-female unicode value ("\uf1fd").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TorsoFemale = "\uf1fd";

        /// <summary>
        /// fa-torso unicode value ("\uf1fe").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Torso = "\uf1fe";

        /// <summary>
        /// fa-torsos-all-female unicode value ("\uf1ff").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TorsosAllFemale = "\uf1ff";

        /// <summary>
        /// fa-torsos-all unicode value ("\uf200").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TorsosAll = "\uf200";

        /// <summary>
        /// fa-torsos-female-male unicode value ("\uf201").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TorsosFemaleMale = "\uf201";

        /// <summary>
        /// fa-torsos-male-female unicode value ("\uf202").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TorsosMaleFemale = "\uf202";

        /// <summary>
        /// fa-torsos unicode value ("\uf203").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Torsos = "\uf203";

        /// <summary>
        /// fa-trash unicode value ("\uf204").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Trash = "\uf204";

        /// <summary>
        /// fa-trees unicode value ("\uf205").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Trees = "\uf205";

        /// <summary>
        /// fa-trophy unicode value ("\uf206").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Trophy = "\uf206";

        /// <summary>
        /// fa-underline unicode value ("\uf207").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Underline = "\uf207";

        /// <summary>
        /// fa-universal-access unicode value ("\uf208").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string UniversalAccess = "\uf208";

        /// <summary>
        /// fa-unlink unicode value ("\uf209").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Unlink = "\uf209";

        /// <summary>
        /// fa-unlock unicode value ("\uf20a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Unlock = "\uf20a";

        /// <summary>
        /// fa-upload-cloud unicode value ("\uf20b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string UploadCloud = "\uf20b";

        /// <summary>
        /// fa-upload unicode value ("\uf20c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Upload = "\uf20c";

        /// <summary>
        /// fa-usb unicode value ("\uf20d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Usb = "\uf20d";

        /// <summary>
        /// fa-video unicode value ("\uf20e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Video = "\uf20e";

        /// <summary>
        /// fa-volume-none unicode value ("\uf20f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string VolumeNone = "\uf20f";

        /// <summary>
        /// fa-volume-strike unicode value ("\uf210").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string VolumeStrike = "\uf210";

        /// <summary>
        /// fa-volume unicode value ("\uf211").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Volume = "\uf211";

        /// <summary>
        /// fa-web unicode value ("\uf212").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Web = "\uf212";

        /// <summary>
        /// fa-wheelchair unicode value ("\uf213").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Wheelchair = "\uf213";

        /// <summary>
        /// fa-widget unicode value ("\uf214").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Widget = "\uf214";

        /// <summary>
        /// fa-wrench unicode value ("\uf215").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Wrench = "\uf215";

        /// <summary>
        /// fa-x-circle unicode value ("\uf216").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string XCircle = "\uf216";

        /// <summary>
        /// fa-x unicode value ("\uf217").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string X = "\uf217";

        /// <summary>
        /// fa-yen unicode value ("\uf218").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Yen = "\uf218";

        /// <summary>
        /// fa-zoom-in unicode value ("\uf219").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ZoomIn = "\uf219";

        /// <summary>
        /// fa-zoom-out unicode value ("\uf21a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ZoomOut = "\uf21a";
    }
}
