using System;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by GlyphJsonToCsharp.
    /// </summary>
    public static partial class OcticonsFont
    {
        /// <summary>
        /// fa-alert unicode value ("\uf100").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Alert = "\uf100";

        /// <summary>
        /// fa-archive unicode value ("\uf101").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Archive = "\uf101";

        /// <summary>
        /// fa-arrow-both unicode value ("\uf102").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowBoth = "\uf102";

        /// <summary>
        /// fa-arrow-down unicode value ("\uf103").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowDown = "\uf103";

        /// <summary>
        /// fa-arrow-left unicode value ("\uf104").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowLeft = "\uf104";

        /// <summary>
        /// fa-arrow-right unicode value ("\uf105").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowRight = "\uf105";

        /// <summary>
        /// fa-arrow-small-down unicode value ("\uf106").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowSmallDown = "\uf106";

        /// <summary>
        /// fa-arrow-small-left unicode value ("\uf107").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowSmallLeft = "\uf107";

        /// <summary>
        /// fa-arrow-small-right unicode value ("\uf108").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowSmallRight = "\uf108";

        /// <summary>
        /// fa-arrow-small-up unicode value ("\uf109").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowSmallUp = "\uf109";

        /// <summary>
        /// fa-arrow-up unicode value ("\uf10a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowUp = "\uf10a";

        /// <summary>
        /// fa-beaker unicode value ("\uf10b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Beaker = "\uf10b";

        /// <summary>
        /// fa-bell unicode value ("\uf10c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bell = "\uf10c";

        /// <summary>
        /// fa-bold unicode value ("\uf10d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bold = "\uf10d";

        /// <summary>
        /// fa-book unicode value ("\uf10e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Book = "\uf10e";

        /// <summary>
        /// fa-bookmark unicode value ("\uf10f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bookmark = "\uf10f";

        /// <summary>
        /// fa-briefcase unicode value ("\uf110").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Briefcase = "\uf110";

        /// <summary>
        /// fa-broadcast unicode value ("\uf111").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Broadcast = "\uf111";

        /// <summary>
        /// fa-browser unicode value ("\uf112").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Browser = "\uf112";

        /// <summary>
        /// fa-bug unicode value ("\uf113").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bug = "\uf113";

        /// <summary>
        /// fa-calendar unicode value ("\uf114").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Calendar = "\uf114";

        /// <summary>
        /// fa-check unicode value ("\uf115").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Check = "\uf115";

        /// <summary>
        /// fa-checklist unicode value ("\uf116").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Checklist = "\uf116";

        /// <summary>
        /// fa-chevron-down unicode value ("\uf117").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ChevronDown = "\uf117";

        /// <summary>
        /// fa-chevron-left unicode value ("\uf118").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ChevronLeft = "\uf118";

        /// <summary>
        /// fa-chevron-right unicode value ("\uf119").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ChevronRight = "\uf119";

        /// <summary>
        /// fa-chevron-up unicode value ("\uf11a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ChevronUp = "\uf11a";

        /// <summary>
        /// fa-circle-slash unicode value ("\uf11b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CircleSlash = "\uf11b";

        /// <summary>
        /// fa-circuit-board unicode value ("\uf11c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CircuitBoard = "\uf11c";

        /// <summary>
        /// fa-clippy unicode value ("\uf11d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Clippy = "\uf11d";

        /// <summary>
        /// fa-clock unicode value ("\uf11e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Clock = "\uf11e";

        /// <summary>
        /// fa-cloud-download unicode value ("\uf11f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CloudDownload = "\uf11f";

        /// <summary>
        /// fa-cloud-upload unicode value ("\uf120").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CloudUpload = "\uf120";

        /// <summary>
        /// fa-code unicode value ("\uf121").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Code = "\uf121";

        /// <summary>
        /// fa-comment unicode value ("\uf122").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Comment = "\uf122";

        /// <summary>
        /// fa-comment-discussion unicode value ("\uf123").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CommentDiscussion = "\uf123";

        /// <summary>
        /// fa-credit-card unicode value ("\uf124").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CreditCard = "\uf124";

        /// <summary>
        /// fa-dash unicode value ("\uf125").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Dash = "\uf125";

        /// <summary>
        /// fa-dashboard unicode value ("\uf126").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Dashboard = "\uf126";

        /// <summary>
        /// fa-database unicode value ("\uf127").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Database = "\uf127";

        /// <summary>
        /// fa-desktop-download unicode value ("\uf128").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DesktopDownload = "\uf128";

        /// <summary>
        /// fa-device-camera unicode value ("\uf129").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DeviceCamera = "\uf129";

        /// <summary>
        /// fa-device-camera-video unicode value ("\uf12a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DeviceCameraVideo = "\uf12a";

        /// <summary>
        /// fa-device-desktop unicode value ("\uf12b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DeviceDesktop = "\uf12b";

        /// <summary>
        /// fa-device-mobile unicode value ("\uf12c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DeviceMobile = "\uf12c";

        /// <summary>
        /// fa-diff unicode value ("\uf12d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Diff = "\uf12d";

        /// <summary>
        /// fa-diff-added unicode value ("\uf12e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DiffAdded = "\uf12e";

        /// <summary>
        /// fa-diff-ignored unicode value ("\uf12f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DiffIgnored = "\uf12f";

        /// <summary>
        /// fa-diff-modified unicode value ("\uf130").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DiffModified = "\uf130";

        /// <summary>
        /// fa-diff-removed unicode value ("\uf131").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DiffRemoved = "\uf131";

        /// <summary>
        /// fa-diff-renamed unicode value ("\uf132").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string DiffRenamed = "\uf132";

        /// <summary>
        /// fa-ellipsis unicode value ("\uf133").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Ellipsis = "\uf133";

        /// <summary>
        /// fa-eye unicode value ("\uf134").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Eye = "\uf134";

        /// <summary>
        /// fa-eye-closed unicode value ("\uf135").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string EyeClosed = "\uf135";

        /// <summary>
        /// fa-file unicode value ("\uf136").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string File = "\uf136";

        /// <summary>
        /// fa-file-binary unicode value ("\uf137").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FileBinary = "\uf137";

        /// <summary>
        /// fa-file-code unicode value ("\uf138").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FileCode = "\uf138";

        /// <summary>
        /// fa-file-directory unicode value ("\uf139").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FileDirectory = "\uf139";

        /// <summary>
        /// fa-file-media unicode value ("\uf13a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FileMedia = "\uf13a";

        /// <summary>
        /// fa-file-pdf unicode value ("\uf13b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FilePdf = "\uf13b";

        /// <summary>
        /// fa-file-submodule unicode value ("\uf13c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FileSubmodule = "\uf13c";

        /// <summary>
        /// fa-file-symlink-directory unicode value ("\uf13d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FileSymlinkDirectory = "\uf13d";

        /// <summary>
        /// fa-file-symlink-file unicode value ("\uf13e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FileSymlinkFile = "\uf13e";

        /// <summary>
        /// fa-file-zip unicode value ("\uf13f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FileZip = "\uf13f";

        /// <summary>
        /// fa-flame unicode value ("\uf140").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Flame = "\uf140";

        /// <summary>
        /// fa-fold unicode value ("\uf141").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Fold = "\uf141";

        /// <summary>
        /// fa-fold-down unicode value ("\uf142").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FoldDown = "\uf142";

        /// <summary>
        /// fa-fold-up unicode value ("\uf143").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FoldUp = "\uf143";

        /// <summary>
        /// fa-gear unicode value ("\uf144").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Gear = "\uf144";

        /// <summary>
        /// fa-gift unicode value ("\uf145").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Gift = "\uf145";

        /// <summary>
        /// fa-gist unicode value ("\uf146").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Gist = "\uf146";

        /// <summary>
        /// fa-gist-secret unicode value ("\uf147").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GistSecret = "\uf147";

        /// <summary>
        /// fa-git-branch unicode value ("\uf148").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GitBranch = "\uf148";

        /// <summary>
        /// fa-git-commit unicode value ("\uf149").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GitCommit = "\uf149";

        /// <summary>
        /// fa-git-compare unicode value ("\uf14a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GitCompare = "\uf14a";

        /// <summary>
        /// fa-git-merge unicode value ("\uf14b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GitMerge = "\uf14b";

        /// <summary>
        /// fa-git-pull-request unicode value ("\uf14c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GitPullRequest = "\uf14c";

        /// <summary>
        /// fa-github-action unicode value ("\uf14d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GithubAction = "\uf14d";

        /// <summary>
        /// fa-globe unicode value ("\uf14e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Globe = "\uf14e";

        /// <summary>
        /// fa-grabber unicode value ("\uf14f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Grabber = "\uf14f";

        /// <summary>
        /// fa-graph unicode value ("\uf150").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Graph = "\uf150";

        /// <summary>
        /// fa-heart unicode value ("\uf151").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Heart = "\uf151";

        /// <summary>
        /// fa-history unicode value ("\uf152").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string History = "\uf152";

        /// <summary>
        /// fa-home unicode value ("\uf153").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Home = "\uf153";

        /// <summary>
        /// fa-horizontal-rule unicode value ("\uf154").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string HorizontalRule = "\uf154";

        /// <summary>
        /// fa-hubot unicode value ("\uf155").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Hubot = "\uf155";

        /// <summary>
        /// fa-inbox unicode value ("\uf156").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Inbox = "\uf156";

        /// <summary>
        /// fa-info unicode value ("\uf157").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Info = "\uf157";

        /// <summary>
        /// fa-issue-closed unicode value ("\uf158").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string IssueClosed = "\uf158";

        /// <summary>
        /// fa-issue-opened unicode value ("\uf159").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string IssueOpened = "\uf159";

        /// <summary>
        /// fa-issue-reopened unicode value ("\uf15a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string IssueReopened = "\uf15a";

        /// <summary>
        /// fa-italic unicode value ("\uf15b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Italic = "\uf15b";

        /// <summary>
        /// fa-jersey unicode value ("\uf15c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Jersey = "\uf15c";

        /// <summary>
        /// fa-kebab-horizontal unicode value ("\uf15d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string KebabHorizontal = "\uf15d";

        /// <summary>
        /// fa-kebab-vertical unicode value ("\uf15e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string KebabVertical = "\uf15e";

        /// <summary>
        /// fa-key unicode value ("\uf15f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Key = "\uf15f";

        /// <summary>
        /// fa-keyboard unicode value ("\uf160").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Keyboard = "\uf160";

        /// <summary>
        /// fa-law unicode value ("\uf161").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Law = "\uf161";

        /// <summary>
        /// fa-light-bulb unicode value ("\uf162").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string LightBulb = "\uf162";

        /// <summary>
        /// fa-link unicode value ("\uf163").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Link = "\uf163";

        /// <summary>
        /// fa-link-external unicode value ("\uf164").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string LinkExternal = "\uf164";

        /// <summary>
        /// fa-list-ordered unicode value ("\uf165").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ListOrdered = "\uf165";

        /// <summary>
        /// fa-list-unordered unicode value ("\uf166").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ListUnordered = "\uf166";

        /// <summary>
        /// fa-location unicode value ("\uf167").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Location = "\uf167";

        /// <summary>
        /// fa-lock unicode value ("\uf168").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Lock = "\uf168";

        /// <summary>
        /// fa-logo-gist unicode value ("\uf169").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string LogoGist = "\uf169";

        /// <summary>
        /// fa-logo-github unicode value ("\uf16a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string LogoGithub = "\uf16a";

        /// <summary>
        /// fa-mail unicode value ("\uf16b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Mail = "\uf16b";

        /// <summary>
        /// fa-mail-read unicode value ("\uf16c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MailRead = "\uf16c";

        /// <summary>
        /// fa-mark-github unicode value ("\uf16d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MarkGithub = "\uf16d";

        /// <summary>
        /// fa-markdown unicode value ("\uf16e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Markdown = "\uf16e";

        /// <summary>
        /// fa-megaphone unicode value ("\uf16f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Megaphone = "\uf16f";

        /// <summary>
        /// fa-mention unicode value ("\uf170").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Mention = "\uf170";

        /// <summary>
        /// fa-milestone unicode value ("\uf171").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Milestone = "\uf171";

        /// <summary>
        /// fa-mirror unicode value ("\uf172").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Mirror = "\uf172";

        /// <summary>
        /// fa-mortar-board unicode value ("\uf173").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MortarBoard = "\uf173";

        /// <summary>
        /// fa-mute unicode value ("\uf174").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Mute = "\uf174";

        /// <summary>
        /// fa-no-newline unicode value ("\uf175").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string NoNewline = "\uf175";

        /// <summary>
        /// fa-note unicode value ("\uf176").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Note = "\uf176";

        /// <summary>
        /// fa-octoface unicode value ("\uf177").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Octoface = "\uf177";

        /// <summary>
        /// fa-organization unicode value ("\uf178").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Organization = "\uf178";

        /// <summary>
        /// fa-package unicode value ("\uf179").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Package = "\uf179";

        /// <summary>
        /// fa-paintcan unicode value ("\uf17a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Paintcan = "\uf17a";

        /// <summary>
        /// fa-pencil unicode value ("\uf17b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pencil = "\uf17b";

        /// <summary>
        /// fa-person unicode value ("\uf17c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Person = "\uf17c";

        /// <summary>
        /// fa-pin unicode value ("\uf17d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pin = "\uf17d";

        /// <summary>
        /// fa-play unicode value ("\uf17e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Play = "\uf17e";

        /// <summary>
        /// fa-plug unicode value ("\uf17f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Plug = "\uf17f";

        /// <summary>
        /// fa-plus unicode value ("\uf180").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Plus = "\uf180";

        /// <summary>
        /// fa-plus-small unicode value ("\uf181").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PlusSmall = "\uf181";

        /// <summary>
        /// fa-primitive-dot unicode value ("\uf182").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PrimitiveDot = "\uf182";

        /// <summary>
        /// fa-primitive-square unicode value ("\uf183").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PrimitiveSquare = "\uf183";

        /// <summary>
        /// fa-project unicode value ("\uf184").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Project = "\uf184";

        /// <summary>
        /// fa-pulse unicode value ("\uf185").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pulse = "\uf185";

        /// <summary>
        /// fa-question unicode value ("\uf186").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Question = "\uf186";

        /// <summary>
        /// fa-quote unicode value ("\uf187").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Quote = "\uf187";

        /// <summary>
        /// fa-radio-tower unicode value ("\uf188").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string RadioTower = "\uf188";

        /// <summary>
        /// fa-reply unicode value ("\uf189").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Reply = "\uf189";

        /// <summary>
        /// fa-repo unicode value ("\uf18a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Repo = "\uf18a";

        /// <summary>
        /// fa-repo-clone unicode value ("\uf18b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string RepoClone = "\uf18b";

        /// <summary>
        /// fa-repo-force-push unicode value ("\uf18c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string RepoForcePush = "\uf18c";

        /// <summary>
        /// fa-repo-forked unicode value ("\uf18d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string RepoForked = "\uf18d";

        /// <summary>
        /// fa-repo-pull unicode value ("\uf18e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string RepoPull = "\uf18e";

        /// <summary>
        /// fa-repo-push unicode value ("\uf18f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string RepoPush = "\uf18f";

        /// <summary>
        /// fa-report unicode value ("\uf190").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Report = "\uf190";

        /// <summary>
        /// fa-request-changes unicode value ("\uf191").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string RequestChanges = "\uf191";

        /// <summary>
        /// fa-rocket unicode value ("\uf192").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Rocket = "\uf192";

        /// <summary>
        /// fa-rss unicode value ("\uf193").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Rss = "\uf193";

        /// <summary>
        /// fa-ruby unicode value ("\uf194").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Ruby = "\uf194";

        /// <summary>
        /// fa-screen-full unicode value ("\uf195").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScreenFull = "\uf195";

        /// <summary>
        /// fa-screen-normal unicode value ("\uf196").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScreenNormal = "\uf196";

        /// <summary>
        /// fa-search unicode value ("\uf197").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Search = "\uf197";

        /// <summary>
        /// fa-server unicode value ("\uf198").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Server = "\uf198";

        /// <summary>
        /// fa-settings unicode value ("\uf199").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Settings = "\uf199";

        /// <summary>
        /// fa-shield unicode value ("\uf19a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Shield = "\uf19a";

        /// <summary>
        /// fa-sign-in unicode value ("\uf19b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SignIn = "\uf19b";

        /// <summary>
        /// fa-sign-out unicode value ("\uf19c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SignOut = "\uf19c";

        /// <summary>
        /// fa-smiley unicode value ("\uf19d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Smiley = "\uf19d";

        /// <summary>
        /// fa-squirrel unicode value ("\uf19e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Squirrel = "\uf19e";

        /// <summary>
        /// fa-star unicode value ("\uf19f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Star = "\uf19f";

        /// <summary>
        /// fa-stop unicode value ("\uf1a0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Stop = "\uf1a0";

        /// <summary>
        /// fa-sync unicode value ("\uf1a1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Sync = "\uf1a1";

        /// <summary>
        /// fa-tag unicode value ("\uf1a2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Tag = "\uf1a2";

        /// <summary>
        /// fa-tasklist unicode value ("\uf1a3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Tasklist = "\uf1a3";

        /// <summary>
        /// fa-telescope unicode value ("\uf1a4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Telescope = "\uf1a4";

        /// <summary>
        /// fa-terminal unicode value ("\uf1a5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Terminal = "\uf1a5";

        /// <summary>
        /// fa-text-size unicode value ("\uf1a6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TextSize = "\uf1a6";

        /// <summary>
        /// fa-three-bars unicode value ("\uf1a7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ThreeBars = "\uf1a7";

        /// <summary>
        /// fa-thumbsdown unicode value ("\uf1a8").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Thumbsdown = "\uf1a8";

        /// <summary>
        /// fa-thumbsup unicode value ("\uf1a9").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Thumbsup = "\uf1a9";

        /// <summary>
        /// fa-tools unicode value ("\uf1aa").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Tools = "\uf1aa";

        /// <summary>
        /// fa-trashcan unicode value ("\uf1ab").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Trashcan = "\uf1ab";

        /// <summary>
        /// fa-triangle-down unicode value ("\uf1ac").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TriangleDown = "\uf1ac";

        /// <summary>
        /// fa-triangle-left unicode value ("\uf1ad").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TriangleLeft = "\uf1ad";

        /// <summary>
        /// fa-triangle-right unicode value ("\uf1ae").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TriangleRight = "\uf1ae";

        /// <summary>
        /// fa-triangle-up unicode value ("\uf1af").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string TriangleUp = "\uf1af";

        /// <summary>
        /// fa-unfold unicode value ("\uf1b0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Unfold = "\uf1b0";

        /// <summary>
        /// fa-unmute unicode value ("\uf1b1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Unmute = "\uf1b1";

        /// <summary>
        /// fa-unverified unicode value ("\uf1b2").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Unverified = "\uf1b2";

        /// <summary>
        /// fa-verified unicode value ("\uf1b3").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Verified = "\uf1b3";

        /// <summary>
        /// fa-versions unicode value ("\uf1b4").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Versions = "\uf1b4";

        /// <summary>
        /// fa-watch unicode value ("\uf1b5").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Watch = "\uf1b5";

        /// <summary>
        /// fa-x unicode value ("\uf1b6").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string X = "\uf1b6";

        /// <summary>
        /// fa-zap unicode value ("\uf1b7").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Zap = "\uf1b7";
    }
}
