using System;

namespace VectorIcons
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by GlyphJsonToCsharp.
    /// </summary>
    public static partial class SimpleLineIconsFont
    {
        /// <summary>
        /// fa-user unicode value ("\ue005").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string User = "\ue005";

        /// <summary>
        /// fa-people unicode value ("\ue001").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string People = "\ue001";

        /// <summary>
        /// fa-user-female unicode value ("\ue000").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string UserFemale = "\ue000";

        /// <summary>
        /// fa-user-follow unicode value ("\ue002").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string UserFollow = "\ue002";

        /// <summary>
        /// fa-user-following unicode value ("\ue003").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string UserFollowing = "\ue003";

        /// <summary>
        /// fa-user-unfollow unicode value ("\ue004").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string UserUnfollow = "\ue004";

        /// <summary>
        /// fa-login unicode value ("\ue066").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Login = "\ue066";

        /// <summary>
        /// fa-logout unicode value ("\ue065").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Logout = "\ue065";

        /// <summary>
        /// fa-emotsmile unicode value ("\ue021").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Emotsmile = "\ue021";

        /// <summary>
        /// fa-phone unicode value ("\ue600").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Phone = "\ue600";

        /// <summary>
        /// fa-call-end unicode value ("\ue048").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CallEnd = "\ue048";

        /// <summary>
        /// fa-call-in unicode value ("\ue047").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CallIn = "\ue047";

        /// <summary>
        /// fa-call-out unicode value ("\ue046").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CallOut = "\ue046";

        /// <summary>
        /// fa-map unicode value ("\ue033").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Map = "\ue033";

        /// <summary>
        /// fa-location-pin unicode value ("\ue096").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string LocationPin = "\ue096";

        /// <summary>
        /// fa-direction unicode value ("\ue042").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Direction = "\ue042";

        /// <summary>
        /// fa-directions unicode value ("\ue041").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Directions = "\ue041";

        /// <summary>
        /// fa-compass unicode value ("\ue045").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Compass = "\ue045";

        /// <summary>
        /// fa-layers unicode value ("\ue034").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Layers = "\ue034";

        /// <summary>
        /// fa-menu unicode value ("\ue601").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Menu = "\ue601";

        /// <summary>
        /// fa-list unicode value ("\ue067").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string List = "\ue067";

        /// <summary>
        /// fa-options-vertical unicode value ("\ue602").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string OptionsVertical = "\ue602";

        /// <summary>
        /// fa-options unicode value ("\ue603").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Options = "\ue603";

        /// <summary>
        /// fa-arrow-down unicode value ("\ue604").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowDown = "\ue604";

        /// <summary>
        /// fa-arrow-left unicode value ("\ue605").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowLeft = "\ue605";

        /// <summary>
        /// fa-arrow-right unicode value ("\ue606").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowRight = "\ue606";

        /// <summary>
        /// fa-arrow-up unicode value ("\ue607").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowUp = "\ue607";

        /// <summary>
        /// fa-arrow-up-circle unicode value ("\ue078").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowUpCircle = "\ue078";

        /// <summary>
        /// fa-arrow-left-circle unicode value ("\ue07a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowLeftCircle = "\ue07a";

        /// <summary>
        /// fa-arrow-right-circle unicode value ("\ue079").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowRightCircle = "\ue079";

        /// <summary>
        /// fa-arrow-down-circle unicode value ("\ue07b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ArrowDownCircle = "\ue07b";

        /// <summary>
        /// fa-check unicode value ("\ue080").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Check = "\ue080";

        /// <summary>
        /// fa-clock unicode value ("\ue081").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Clock = "\ue081";

        /// <summary>
        /// fa-plus unicode value ("\ue095").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Plus = "\ue095";

        /// <summary>
        /// fa-minus unicode value ("\ue615").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Minus = "\ue615";

        /// <summary>
        /// fa-close unicode value ("\ue082").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Close = "\ue082";

        /// <summary>
        /// fa-event unicode value ("\ue619").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Event = "\ue619";

        /// <summary>
        /// fa-exclamation unicode value ("\ue617").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Exclamation = "\ue617";

        /// <summary>
        /// fa-organization unicode value ("\ue616").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Organization = "\ue616";

        /// <summary>
        /// fa-trophy unicode value ("\ue006").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Trophy = "\ue006";

        /// <summary>
        /// fa-screen-smartphone unicode value ("\ue010").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScreenSmartphone = "\ue010";

        /// <summary>
        /// fa-screen-desktop unicode value ("\ue011").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScreenDesktop = "\ue011";

        /// <summary>
        /// fa-plane unicode value ("\ue012").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Plane = "\ue012";

        /// <summary>
        /// fa-notebook unicode value ("\ue013").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Notebook = "\ue013";

        /// <summary>
        /// fa-mustache unicode value ("\ue014").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Mustache = "\ue014";

        /// <summary>
        /// fa-mouse unicode value ("\ue015").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Mouse = "\ue015";

        /// <summary>
        /// fa-magnet unicode value ("\ue016").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Magnet = "\ue016";

        /// <summary>
        /// fa-energy unicode value ("\ue020").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Energy = "\ue020";

        /// <summary>
        /// fa-disc unicode value ("\ue022").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Disc = "\ue022";

        /// <summary>
        /// fa-cursor unicode value ("\ue06e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Cursor = "\ue06e";

        /// <summary>
        /// fa-cursor-move unicode value ("\ue023").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CursorMove = "\ue023";

        /// <summary>
        /// fa-crop unicode value ("\ue024").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Crop = "\ue024";

        /// <summary>
        /// fa-chemistry unicode value ("\ue026").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Chemistry = "\ue026";

        /// <summary>
        /// fa-speedometer unicode value ("\ue007").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Speedometer = "\ue007";

        /// <summary>
        /// fa-shield unicode value ("\ue00e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Shield = "\ue00e";

        /// <summary>
        /// fa-screen-tablet unicode value ("\ue00f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ScreenTablet = "\ue00f";

        /// <summary>
        /// fa-magic-wand unicode value ("\ue017").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MagicWand = "\ue017";

        /// <summary>
        /// fa-hourglass unicode value ("\ue018").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Hourglass = "\ue018";

        /// <summary>
        /// fa-graduation unicode value ("\ue019").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Graduation = "\ue019";

        /// <summary>
        /// fa-ghost unicode value ("\ue01a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Ghost = "\ue01a";

        /// <summary>
        /// fa-game-controller unicode value ("\ue01b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GameController = "\ue01b";

        /// <summary>
        /// fa-fire unicode value ("\ue01c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Fire = "\ue01c";

        /// <summary>
        /// fa-eyeglass unicode value ("\ue01d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Eyeglass = "\ue01d";

        /// <summary>
        /// fa-envelope-open unicode value ("\ue01e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string EnvelopeOpen = "\ue01e";

        /// <summary>
        /// fa-envelope-letter unicode value ("\ue01f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string EnvelopeLetter = "\ue01f";

        /// <summary>
        /// fa-bell unicode value ("\ue027").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bell = "\ue027";

        /// <summary>
        /// fa-badge unicode value ("\ue028").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Badge = "\ue028";

        /// <summary>
        /// fa-anchor unicode value ("\ue029").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Anchor = "\ue029";

        /// <summary>
        /// fa-wallet unicode value ("\ue02a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Wallet = "\ue02a";

        /// <summary>
        /// fa-vector unicode value ("\ue02b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Vector = "\ue02b";

        /// <summary>
        /// fa-speech unicode value ("\ue02c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Speech = "\ue02c";

        /// <summary>
        /// fa-puzzle unicode value ("\ue02d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Puzzle = "\ue02d";

        /// <summary>
        /// fa-printer unicode value ("\ue02e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Printer = "\ue02e";

        /// <summary>
        /// fa-present unicode value ("\ue02f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Present = "\ue02f";

        /// <summary>
        /// fa-playlist unicode value ("\ue030").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Playlist = "\ue030";

        /// <summary>
        /// fa-pin unicode value ("\ue031").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pin = "\ue031";

        /// <summary>
        /// fa-picture unicode value ("\ue032").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Picture = "\ue032";

        /// <summary>
        /// fa-handbag unicode value ("\ue035").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Handbag = "\ue035";

        /// <summary>
        /// fa-globe-alt unicode value ("\ue036").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string GlobeAlt = "\ue036";

        /// <summary>
        /// fa-globe unicode value ("\ue037").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Globe = "\ue037";

        /// <summary>
        /// fa-folder-alt unicode value ("\ue039").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string FolderAlt = "\ue039";

        /// <summary>
        /// fa-folder unicode value ("\ue089").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Folder = "\ue089";

        /// <summary>
        /// fa-film unicode value ("\ue03a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Film = "\ue03a";

        /// <summary>
        /// fa-feed unicode value ("\ue03b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Feed = "\ue03b";

        /// <summary>
        /// fa-drop unicode value ("\ue03e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Drop = "\ue03e";

        /// <summary>
        /// fa-drawer unicode value ("\ue03f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Drawer = "\ue03f";

        /// <summary>
        /// fa-docs unicode value ("\ue040").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Docs = "\ue040";

        /// <summary>
        /// fa-doc unicode value ("\ue085").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Doc = "\ue085";

        /// <summary>
        /// fa-diamond unicode value ("\ue043").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Diamond = "\ue043";

        /// <summary>
        /// fa-cup unicode value ("\ue044").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Cup = "\ue044";

        /// <summary>
        /// fa-calculator unicode value ("\ue049").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Calculator = "\ue049";

        /// <summary>
        /// fa-bubbles unicode value ("\ue04a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bubbles = "\ue04a";

        /// <summary>
        /// fa-briefcase unicode value ("\ue04b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Briefcase = "\ue04b";

        /// <summary>
        /// fa-book-open unicode value ("\ue04c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string BookOpen = "\ue04c";

        /// <summary>
        /// fa-basket-loaded unicode value ("\ue04d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string BasketLoaded = "\ue04d";

        /// <summary>
        /// fa-basket unicode value ("\ue04e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Basket = "\ue04e";

        /// <summary>
        /// fa-bag unicode value ("\ue04f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bag = "\ue04f";

        /// <summary>
        /// fa-action-undo unicode value ("\ue050").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ActionUndo = "\ue050";

        /// <summary>
        /// fa-action-redo unicode value ("\ue051").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ActionRedo = "\ue051";

        /// <summary>
        /// fa-wrench unicode value ("\ue052").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Wrench = "\ue052";

        /// <summary>
        /// fa-umbrella unicode value ("\ue053").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Umbrella = "\ue053";

        /// <summary>
        /// fa-trash unicode value ("\ue054").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Trash = "\ue054";

        /// <summary>
        /// fa-tag unicode value ("\ue055").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Tag = "\ue055";

        /// <summary>
        /// fa-support unicode value ("\ue056").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Support = "\ue056";

        /// <summary>
        /// fa-frame unicode value ("\ue038").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Frame = "\ue038";

        /// <summary>
        /// fa-size-fullscreen unicode value ("\ue057").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SizeFullscreen = "\ue057";

        /// <summary>
        /// fa-size-actual unicode value ("\ue058").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SizeActual = "\ue058";

        /// <summary>
        /// fa-shuffle unicode value ("\ue059").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Shuffle = "\ue059";

        /// <summary>
        /// fa-share-alt unicode value ("\ue05a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ShareAlt = "\ue05a";

        /// <summary>
        /// fa-share unicode value ("\ue05b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Share = "\ue05b";

        /// <summary>
        /// fa-rocket unicode value ("\ue05c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Rocket = "\ue05c";

        /// <summary>
        /// fa-question unicode value ("\ue05d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Question = "\ue05d";

        /// <summary>
        /// fa-pie-chart unicode value ("\ue05e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PieChart = "\ue05e";

        /// <summary>
        /// fa-pencil unicode value ("\ue05f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pencil = "\ue05f";

        /// <summary>
        /// fa-note unicode value ("\ue060").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Note = "\ue060";

        /// <summary>
        /// fa-loop unicode value ("\ue064").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Loop = "\ue064";

        /// <summary>
        /// fa-home unicode value ("\ue069").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Home = "\ue069";

        /// <summary>
        /// fa-grid unicode value ("\ue06a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Grid = "\ue06a";

        /// <summary>
        /// fa-graph unicode value ("\ue06b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Graph = "\ue06b";

        /// <summary>
        /// fa-microphone unicode value ("\ue063").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Microphone = "\ue063";

        /// <summary>
        /// fa-music-tone-alt unicode value ("\ue061").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MusicToneAlt = "\ue061";

        /// <summary>
        /// fa-music-tone unicode value ("\ue062").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MusicTone = "\ue062";

        /// <summary>
        /// fa-earphones-alt unicode value ("\ue03c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string EarphonesAlt = "\ue03c";

        /// <summary>
        /// fa-earphones unicode value ("\ue03d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Earphones = "\ue03d";

        /// <summary>
        /// fa-equalizer unicode value ("\ue06c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Equalizer = "\ue06c";

        /// <summary>
        /// fa-like unicode value ("\ue068").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Like = "\ue068";

        /// <summary>
        /// fa-dislike unicode value ("\ue06d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Dislike = "\ue06d";

        /// <summary>
        /// fa-control-start unicode value ("\ue06f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ControlStart = "\ue06f";

        /// <summary>
        /// fa-control-rewind unicode value ("\ue070").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ControlRewind = "\ue070";

        /// <summary>
        /// fa-control-play unicode value ("\ue071").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ControlPlay = "\ue071";

        /// <summary>
        /// fa-control-pause unicode value ("\ue072").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ControlPause = "\ue072";

        /// <summary>
        /// fa-control-forward unicode value ("\ue073").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ControlForward = "\ue073";

        /// <summary>
        /// fa-control-end unicode value ("\ue074").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string ControlEnd = "\ue074";

        /// <summary>
        /// fa-volume-1 unicode value ("\ue09f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Volume1 = "\ue09f";

        /// <summary>
        /// fa-volume-2 unicode value ("\ue0a0").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Volume2 = "\ue0a0";

        /// <summary>
        /// fa-volume-off unicode value ("\ue0a1").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string VolumeOff = "\ue0a1";

        /// <summary>
        /// fa-calendar unicode value ("\ue075").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Calendar = "\ue075";

        /// <summary>
        /// fa-bulb unicode value ("\ue076").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bulb = "\ue076";

        /// <summary>
        /// fa-chart unicode value ("\ue077").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Chart = "\ue077";

        /// <summary>
        /// fa-ban unicode value ("\ue07c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Ban = "\ue07c";

        /// <summary>
        /// fa-bubble unicode value ("\ue07d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bubble = "\ue07d";

        /// <summary>
        /// fa-camrecorder unicode value ("\ue07e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Camrecorder = "\ue07e";

        /// <summary>
        /// fa-camera unicode value ("\ue07f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Camera = "\ue07f";

        /// <summary>
        /// fa-cloud-download unicode value ("\ue083").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CloudDownload = "\ue083";

        /// <summary>
        /// fa-cloud-upload unicode value ("\ue084").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CloudUpload = "\ue084";

        /// <summary>
        /// fa-envelope unicode value ("\ue086").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Envelope = "\ue086";

        /// <summary>
        /// fa-eye unicode value ("\ue087").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Eye = "\ue087";

        /// <summary>
        /// fa-flag unicode value ("\ue088").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Flag = "\ue088";

        /// <summary>
        /// fa-heart unicode value ("\ue08a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Heart = "\ue08a";

        /// <summary>
        /// fa-info unicode value ("\ue08b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Info = "\ue08b";

        /// <summary>
        /// fa-key unicode value ("\ue08c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Key = "\ue08c";

        /// <summary>
        /// fa-link unicode value ("\ue08d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Link = "\ue08d";

        /// <summary>
        /// fa-lock unicode value ("\ue08e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Lock = "\ue08e";

        /// <summary>
        /// fa-lock-open unicode value ("\ue08f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string LockOpen = "\ue08f";

        /// <summary>
        /// fa-magnifier unicode value ("\ue090").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Magnifier = "\ue090";

        /// <summary>
        /// fa-magnifier-add unicode value ("\ue091").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MagnifierAdd = "\ue091";

        /// <summary>
        /// fa-magnifier-remove unicode value ("\ue092").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string MagnifierRemove = "\ue092";

        /// <summary>
        /// fa-paper-clip unicode value ("\ue093").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PaperClip = "\ue093";

        /// <summary>
        /// fa-paper-plane unicode value ("\ue094").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string PaperPlane = "\ue094";

        /// <summary>
        /// fa-power unicode value ("\ue097").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Power = "\ue097";

        /// <summary>
        /// fa-refresh unicode value ("\ue098").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Refresh = "\ue098";

        /// <summary>
        /// fa-reload unicode value ("\ue099").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Reload = "\ue099";

        /// <summary>
        /// fa-settings unicode value ("\ue09a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Settings = "\ue09a";

        /// <summary>
        /// fa-star unicode value ("\ue09b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Star = "\ue09b";

        /// <summary>
        /// fa-symbol-female unicode value ("\ue09c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SymbolFemale = "\ue09c";

        /// <summary>
        /// fa-symbol-male unicode value ("\ue09d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SymbolMale = "\ue09d";

        /// <summary>
        /// fa-target unicode value ("\ue09e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Target = "\ue09e";

        /// <summary>
        /// fa-credit-card unicode value ("\ue025").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string CreditCard = "\ue025";

        /// <summary>
        /// fa-paypal unicode value ("\ue608").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Paypal = "\ue608";

        /// <summary>
        /// fa-social-tumblr unicode value ("\ue00a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialTumblr = "\ue00a";

        /// <summary>
        /// fa-social-twitter unicode value ("\ue009").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialTwitter = "\ue009";

        /// <summary>
        /// fa-social-facebook unicode value ("\ue00b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialFacebook = "\ue00b";

        /// <summary>
        /// fa-social-instagram unicode value ("\ue609").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialInstagram = "\ue609";

        /// <summary>
        /// fa-social-linkedin unicode value ("\ue60a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialLinkedin = "\ue60a";

        /// <summary>
        /// fa-social-pinterest unicode value ("\ue60b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialPinterest = "\ue60b";

        /// <summary>
        /// fa-social-github unicode value ("\ue60c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialGithub = "\ue60c";

        /// <summary>
        /// fa-social-google unicode value ("\ue60d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialGoogle = "\ue60d";

        /// <summary>
        /// fa-social-reddit unicode value ("\ue60e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialReddit = "\ue60e";

        /// <summary>
        /// fa-social-skype unicode value ("\ue60f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialSkype = "\ue60f";

        /// <summary>
        /// fa-social-dribbble unicode value ("\ue00d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialDribbble = "\ue00d";

        /// <summary>
        /// fa-social-behance unicode value ("\ue610").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialBehance = "\ue610";

        /// <summary>
        /// fa-social-foursqare unicode value ("\ue611").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialFoursqare = "\ue611";

        /// <summary>
        /// fa-social-soundcloud unicode value ("\ue612").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialSoundcloud = "\ue612";

        /// <summary>
        /// fa-social-spotify unicode value ("\ue613").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialSpotify = "\ue613";

        /// <summary>
        /// fa-social-stumbleupon unicode value ("\ue614").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialStumbleupon = "\ue614";

        /// <summary>
        /// fa-social-youtube unicode value ("\ue008").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialYoutube = "\ue008";

        /// <summary>
        /// fa-social-dropbox unicode value ("\ue00c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialDropbox = "\ue00c";

        /// <summary>
        /// fa-social-vkontakte unicode value ("\ue618").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialVkontakte = "\ue618";

        /// <summary>
        /// fa-social-steam unicode value ("\ue620").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string SocialSteam = "\ue620";
    }
}
