using System;

namespace FontAwesome
{
    /// <summary>
    /// The unicode values for all FontAwesome icons.
    /// <para/>
    /// See https://fontawesome.com/cheatsheet
    /// <para/>
    /// This code was automatically generated by GlyphJsonToCsharp.
    /// </summary>
    public static partial class ZocialFont
    {
        /// <summary>
        /// fa-acrobat unicode value ("\uf100").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Acrobat = "\uf100";

        /// <summary>
        /// fa-amazon unicode value ("\uf101").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Amazon = "\uf101";

        /// <summary>
        /// fa-android unicode value ("\uf102").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Android = "\uf102";

        /// <summary>
        /// fa-angellist unicode value ("\uf103").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Angellist = "\uf103";

        /// <summary>
        /// fa-aol unicode value ("\uf104").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Aol = "\uf104";

        /// <summary>
        /// fa-appnet unicode value ("\uf105").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Appnet = "\uf105";

        /// <summary>
        /// fa-appstore unicode value ("\uf106").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Appstore = "\uf106";

        /// <summary>
        /// fa-bitbucket unicode value ("\uf107").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bitbucket = "\uf107";

        /// <summary>
        /// fa-bitcoin unicode value ("\uf108").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Bitcoin = "\uf108";

        /// <summary>
        /// fa-blogger unicode value ("\uf109").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Blogger = "\uf109";

        /// <summary>
        /// fa-buffer unicode value ("\uf10a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Buffer = "\uf10a";

        /// <summary>
        /// fa-cal unicode value ("\uf10b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Cal = "\uf10b";

        /// <summary>
        /// fa-call unicode value ("\uf10c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Call = "\uf10c";

        /// <summary>
        /// fa-cart unicode value ("\uf10d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Cart = "\uf10d";

        /// <summary>
        /// fa-chrome unicode value ("\uf10e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Chrome = "\uf10e";

        /// <summary>
        /// fa-cloudapp unicode value ("\uf10f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Cloudapp = "\uf10f";

        /// <summary>
        /// fa-creativecommons unicode value ("\uf110").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Creativecommons = "\uf110";

        /// <summary>
        /// fa-delicious unicode value ("\uf111").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Delicious = "\uf111";

        /// <summary>
        /// fa-digg unicode value ("\uf112").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Digg = "\uf112";

        /// <summary>
        /// fa-disqus unicode value ("\uf113").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Disqus = "\uf113";

        /// <summary>
        /// fa-dribbble unicode value ("\uf114").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Dribbble = "\uf114";

        /// <summary>
        /// fa-dropbox unicode value ("\uf115").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Dropbox = "\uf115";

        /// <summary>
        /// fa-drupal unicode value ("\uf116").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Drupal = "\uf116";

        /// <summary>
        /// fa-dwolla unicode value ("\uf118").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Dwolla = "\uf118";

        /// <summary>
        /// fa-email unicode value ("\uf119").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Email = "\uf119";

        /// <summary>
        /// fa-eventasaurus unicode value ("\uf11a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Eventasaurus = "\uf11a";

        /// <summary>
        /// fa-eventbrite unicode value ("\uf11b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Eventbrite = "\uf11b";

        /// <summary>
        /// fa-eventful unicode value ("\uf11c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Eventful = "\uf11c";

        /// <summary>
        /// fa-evernote unicode value ("\uf11d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Evernote = "\uf11d";

        /// <summary>
        /// fa-facebook unicode value ("\uf11e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Facebook = "\uf11e";

        /// <summary>
        /// fa-fivehundredpx unicode value ("\uf11f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Fivehundredpx = "\uf11f";

        /// <summary>
        /// fa-flattr unicode value ("\uf120").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Flattr = "\uf120";

        /// <summary>
        /// fa-flickr unicode value ("\uf121").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Flickr = "\uf121";

        /// <summary>
        /// fa-forrst unicode value ("\uf122").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Forrst = "\uf122";

        /// <summary>
        /// fa-foursquare unicode value ("\uf123").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Foursquare = "\uf123";

        /// <summary>
        /// fa-github unicode value ("\uf124").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Github = "\uf124";

        /// <summary>
        /// fa-gmail unicode value ("\uf125").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Gmail = "\uf125";

        /// <summary>
        /// fa-google unicode value ("\uf126").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Google = "\uf126";

        /// <summary>
        /// fa-googleplay unicode value ("\uf127").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Googleplay = "\uf127";

        /// <summary>
        /// fa-googleplus unicode value ("\uf128").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Googleplus = "\uf128";

        /// <summary>
        /// fa-gowalla unicode value ("\uf129").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Gowalla = "\uf129";

        /// <summary>
        /// fa-grooveshark unicode value ("\uf12a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Grooveshark = "\uf12a";

        /// <summary>
        /// fa-guest unicode value ("\uf12b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Guest = "\uf12b";

        /// <summary>
        /// fa-html5 unicode value ("\uf12c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Html5 = "\uf12c";

        /// <summary>
        /// fa-ie unicode value ("\uf12d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Ie = "\uf12d";

        /// <summary>
        /// fa-instagram unicode value ("\uf12e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Instagram = "\uf12e";

        /// <summary>
        /// fa-instapaper unicode value ("\uf12f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Instapaper = "\uf12f";

        /// <summary>
        /// fa-intensedebate unicode value ("\uf130").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Intensedebate = "\uf130";

        /// <summary>
        /// fa-itunes unicode value ("\uf131").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Itunes = "\uf131";

        /// <summary>
        /// fa-klout unicode value ("\uf132").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Klout = "\uf132";

        /// <summary>
        /// fa-lanyrd unicode value ("\uf133").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Lanyrd = "\uf133";

        /// <summary>
        /// fa-lastfm unicode value ("\uf134").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Lastfm = "\uf134";

        /// <summary>
        /// fa-lego unicode value ("\uf135").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Lego = "\uf135";

        /// <summary>
        /// fa-linkedin unicode value ("\uf136").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Linkedin = "\uf136";

        /// <summary>
        /// fa-lkdto unicode value ("\uf137").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Lkdto = "\uf137";

        /// <summary>
        /// fa-logmein unicode value ("\uf138").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Logmein = "\uf138";

        /// <summary>
        /// fa-macstore unicode value ("\uf139").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Macstore = "\uf139";

        /// <summary>
        /// fa-meetup unicode value ("\uf13a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Meetup = "\uf13a";

        /// <summary>
        /// fa-myspace unicode value ("\uf13b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Myspace = "\uf13b";

        /// <summary>
        /// fa-ninetyninedesigns unicode value ("\uf13c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Ninetyninedesigns = "\uf13c";

        /// <summary>
        /// fa-openid unicode value ("\uf13d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Openid = "\uf13d";

        /// <summary>
        /// fa-opentable unicode value ("\uf13e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Opentable = "\uf13e";

        /// <summary>
        /// fa-paypal unicode value ("\uf13f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Paypal = "\uf13f";

        /// <summary>
        /// fa-persona unicode value ("\uf164").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Persona = "\uf164";

        /// <summary>
        /// fa-pinboard unicode value ("\uf140").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pinboard = "\uf140";

        /// <summary>
        /// fa-pinterest unicode value ("\uf141").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pinterest = "\uf141";

        /// <summary>
        /// fa-plancast unicode value ("\uf142").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Plancast = "\uf142";

        /// <summary>
        /// fa-plurk unicode value ("\uf143").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Plurk = "\uf143";

        /// <summary>
        /// fa-pocket unicode value ("\uf144").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Pocket = "\uf144";

        /// <summary>
        /// fa-podcast unicode value ("\uf145").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Podcast = "\uf145";

        /// <summary>
        /// fa-posterous unicode value ("\uf146").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Posterous = "\uf146";

        /// <summary>
        /// fa-print unicode value ("\uf147").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Print = "\uf147";

        /// <summary>
        /// fa-quora unicode value ("\uf148").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Quora = "\uf148";

        /// <summary>
        /// fa-reddit unicode value ("\uf149").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Reddit = "\uf149";

        /// <summary>
        /// fa-rss unicode value ("\uf14a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Rss = "\uf14a";

        /// <summary>
        /// fa-scribd unicode value ("\uf14b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Scribd = "\uf14b";

        /// <summary>
        /// fa-skype unicode value ("\uf14c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Skype = "\uf14c";

        /// <summary>
        /// fa-smashing unicode value ("\uf14d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Smashing = "\uf14d";

        /// <summary>
        /// fa-songkick unicode value ("\uf14e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Songkick = "\uf14e";

        /// <summary>
        /// fa-soundcloud unicode value ("\uf14f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Soundcloud = "\uf14f";

        /// <summary>
        /// fa-spotify unicode value ("\uf150").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Spotify = "\uf150";

        /// <summary>
        /// fa-stackoverflow unicode value ("\uf151").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Stackoverflow = "\uf151";

        /// <summary>
        /// fa-statusnet unicode value ("\uf152").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Statusnet = "\uf152";

        /// <summary>
        /// fa-steam unicode value ("\uf153").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Steam = "\uf153";

        /// <summary>
        /// fa-stripe unicode value ("\uf154").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Stripe = "\uf154";

        /// <summary>
        /// fa-stumbleupon unicode value ("\uf155").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Stumbleupon = "\uf155";

        /// <summary>
        /// fa-tumblr unicode value ("\uf156").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Tumblr = "\uf156";

        /// <summary>
        /// fa-twitter unicode value ("\uf157").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Twitter = "\uf157";

        /// <summary>
        /// fa-viadeo unicode value ("\uf158").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Viadeo = "\uf158";

        /// <summary>
        /// fa-vimeo unicode value ("\uf159").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Vimeo = "\uf159";

        /// <summary>
        /// fa-vk unicode value ("\uf15a").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Vk = "\uf15a";

        /// <summary>
        /// fa-weibo unicode value ("\uf15b").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Weibo = "\uf15b";

        /// <summary>
        /// fa-wikipedia unicode value ("\uf15c").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Wikipedia = "\uf15c";

        /// <summary>
        /// fa-windows unicode value ("\uf15d").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Windows = "\uf15d";

        /// <summary>
        /// fa-wordpress unicode value ("\uf15e").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Wordpress = "\uf15e";

        /// <summary>
        /// fa-xing unicode value ("\uf15f").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Xing = "\uf15f";

        /// <summary>
        /// fa-yahoo unicode value ("\uf160").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Yahoo = "\uf160";

        /// <summary>
        /// fa-ycombinator unicode value ("\uf161").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Ycombinator = "\uf161";

        /// <summary>
        /// fa-yelp unicode value ("\uf162").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Yelp = "\uf162";

        /// <summary>
        /// fa-youtube unicode value ("\uf163").
        /// <para/>
        /// This icon supports the following styles: $styles$
        /// <para/>
        /// See $link$
        /// </summary>
        public const string Youtube = "\uf163";
    }
}
